### ISSUE TITLE
Nová funkce - propojení anonymních uživatelů dvou sociálních bublin

### ISSUE THREAD

**Issue by Petr-Mi** [vexl-it/vexl#1011]
Zdravím,
bylo by fajn přidat funkci na propojení dvou uživatelů prostřednictvím třetího, který je se spojení s nimi.
Tito dva uživatelé na sebe nemohou vidět, protože spolu nesdílí sociální bublinu.
Ale já mohu být ve spojení s oběma. A protože anonymita je základ, nemám ani s jedním odhalenou identitu, tedy nemohu jim vzájemně předat jejich mobilní čísla. Protože např. ani jeden z nás tří nechce odhalit identitu a mobil. Ale přitom jsem s oběma úspěšně a bezpečně vexloval a mám tedy s oběma dobrou zkušenost.

**Comment by leomira** [comment]
Pre tento pripad staci, aby ste si vymenili telefonne cisla (staci si ich jednoducho pridat vo vexli, nemusite si ani odhalovat identitu), a dve protistrany sa cez teba automaticky prepoja @Petr-Mi :)

**Comment by Petr-Mi** [comment]
> Pre tento pripad staci, aby ste si vymenili telefonne cisla (staci si ich jednoducho pridat vo vexli, nemusite si ani odhalovat identitu), a dve protistrany sa cez teba automaticky prepoja @Petr-Mi :)

Ale pak už to nebude anonymní. :-D
A právě anonymita je jednou z předností Vexlu. Tak proč ji porušovat ;-)

**Comment by leomira** [comment]
Jedna z prednosti Vexlu je unikatny reputacny model, ktory ta prepaja s tvojimi znamymi a znamymi znamych. To, co popisujes, tento reputacny model narusuje. 

Cislo si mozes ulozit aj ked vies toho cloveka len nickname, ak ho vies pak identifikovat.

**Comment by Petr-Mi** [comment]
Plno telefonních čísel se dá dohledat na internetu a pak je opět po anonymitě. :-(

**Comment by leomira** [comment]
To je ale uplne ina, nesuvisiaca zalezitost :) 

Diky za diskusiu, ale tuto issue zatvaram.
