### ISSUE TITLE
Change helper to Vekslak

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#1016]
In order to keep the app consistent, I propose changing the warning in our purple box to our Vexlak, same design as we have it on marketplace. 

<img width="392" alt="Snímka obrazovky 2024-04-26 o 12 20 36" src="https://github.com/vexl-it/vexl/assets/25779015/358bc4c7-52c2-44c3-9f46-4a64d1b461ad">

**Comment by SamTremko** [comment]
@leomira after discussion moving this to blocked, as it looks weird and probably needs redesign:

![Image](https://github.com/vexl-it/vexl/assets/32439382/52cbd845-b1cf-4dca-acd0-155d5cd843d9)
