### ISSUE TITLE
It is not clear how to browse multiple requests 

### ISSUE THREAD

**Issue by zaplmi** [vexl-it/vexl#102]
This is an improvement proposal. 

I (and few other people who I consulted this with) don't find browsing multiple offer request clear and intuitive enough:

When you have more request to your offer it is not really clear how to browse these requests. 
After little wrestling I have figured out that you have to swipe left (see video) however it is not obvious so I suggest to guide user little bit more e.g. with following note: **swipe left to see more request.**

https://user-images.githubusercontent.com/91535734/193453935-a455084d-cf8f-40fc-9363-5730ad5aef72.MOV

**Comment by leomira** [comment]
@mpocuch I attach a screenshot from a figma handover file to illustrate how it was proposed in the original design.
Please update the apps accordingly. 

<img width="206" alt="Snímka obrazovky 2022-10-02 o 23 49 47" src="https://user-images.githubusercontent.com/25779015/193477819-30932b6c-04ec-4e81-bedf-cd1d1e10c3b2.png">

**Comment by mpocuch** [comment]
@leomira this is applicable only for iOS, right? we just tested this on AN (both 13 and 12) and on both it showed OK

![Image](https://user-images.githubusercontent.com/113974775/194908603-beff0699-df15-4f72-a23e-9d749f973553.png)

**Comment by leomira** [comment]
it might be the case

**Comment by leomira** [comment]
I am unfortunately unable to test it on Android rn

**Comment by leomira** [comment]
@mpocuch not solved

**Comment by leomira** [comment]
solved for now with the native element, closing this for now
