### ISSUE TITLE
Change when we ask for notifications

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#1020]
Let's kick this off from onboarding and ask the user to allow notifications only when it is really necessary: 

requesting an offer
creating a new offer 

Don't forget to handle declining (particularly on iOS)

**Comment by kaladivo** [comment]
Don't forget to handle rerequest after user declines (after user declines, any subsequent call to `requestPermissions`  returns false without displaying the allow/decline dialog)

**Comment by leomira** [comment]
works flawlessly, good job! 🎉  let's also implement this for chat messages 🙏

**Comment by leomira** [comment]
amazing, amazing progress 🎉
