### ISSUE TITLE
Show Social reach in Profile

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#107]
One step towards gamification of Vexl experience is to provide an information about his social reach in the app. It's a count of 1st+2nd degree contacts with Vexl installed; basically result of ```contacts/me`` API call available for encrypting offers. That way people can see how many people see their offers, and help them follow how the Vexl userbase AND their social reach by building network of contacts is growing.

Proposal:
Add "Reach: xxx vexlers" below nickname to Profile page. Currently the number is updated on app launch and when creating offer, which is enough and we don't need any changes in this logic.

**Comment by leomira** [comment]
+ adding the info to "create offer" (design done)

**Comment by leomira** [comment]
shipped in Vexl 2.0
