### ISSUE TITLE
Term and Conditions not clickable in onboarding

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#1079]
Currently its not possible to view terms and conditions before onboarding in the vexl app. Can we please make the terms and conditions clickable here. 

![telegram-cloud-photo-size-4-5913524051211567476-y](https://github.com/vexl-it/vexl/assets/143531040/ae438c4f-5377-4b71-88e1-709beedecd76)

**Comment by leomira** [comment]
@SamTremko @kaladivo pls check this out, high priority, don't wanna postpone
