### ISSUE TITLE
Show user's registered number in Profile

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#108]
Currently there's no indication what phone number has been used for app verification during onboarding; This can be issue even for normal users with dual SIM phones, not only for paranoid users with plenty of SIMs and degoogled phones ;).

Proposal:
Let's display phone number (just a full number) below nickname in Profile page.

This is relevant to #84, because the phone number is going to be (partly) revealed in Reveal identity.

**Comment by leomira** [comment]
works on Android

**Comment by leomira** [comment]
works on iOS too 🎉
