### ISSUE TITLE
Last chat messages covered by virtual keyboard

### ISSUE THREAD

**Issue by Dehumanizer77** [vexl-it/vexl#112]
When I have a chat open and click the input field to type a message, virtual keyboard pops up and covers last message or a few messages. I then have to scroll up the chat to see the latest conversation, which is inconvenient. 

Android 12, app version 1.0.9 (but this was happening with all older versions as well)

**Comment by prusnak** [comment]
The same issue is with iOS

**Comment by leomira** [comment]
shipped in 1.0.16
