### ISSUE TITLE
"My offer" button inconsistencies 

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#117]
I have paused an offer some time ago and now it's not there anymore.

I have found that when I create a new offer, the old inactive offers are still there, so the problem is only that when there is no active offer, the "my offers" button doesn't show up (but only after some time it disappears, not right away) and instead only the "+" button is there, I suppose this might be a quick fix.

also when I deleted the only active order, the "my offers" button immediately disappeared and there is only the "+" button

**Comment by prusnak** [comment]
I see the same issue with iOS - the offer does not have to be paused

**Comment by leomira** [comment]
I never could reproduce this, can you try if this was fixed in Alpha 1.0.18, @prusnak ?

**Comment by prusnak** [comment]
It seems to me this is fixed in 1.0.18 for iOS
