### ISSUE TITLE
The oldest chat is behind nav-bar

### ISSUE THREAD

**Issue by tomashrib** [vexl-it/vexl#119]
When there are lots of chats, the oldest one is under the navigation bar and it is hard to click on it. You can't scroll down further. 

It should stay above the navigation bar.

![signal-2022-10-21-13-41-43-498.jpg](https://user-images.githubusercontent.com/103599310/197188047-cf9a371c-adc3-476d-aafe-89500b4addd8.jpg)

**Comment by leomira** [comment]
probably relevant to #87

**Comment by leomira** [comment]
relevant to #112

**Comment by leomira** [comment]
shipped in 1.0.16

**Comment by leomira** [comment]
shipped in 1.0.16

**Comment by leomira** [comment]
shipped in 1.0.16
