### ISSUE TITLE
Change the wording, icons and redirect to new website.

### ISSUE THREAD

**Issue by stepanborovka** [vexl-it/vexl#1194]
![IMG_2923](https://github.com/user-attachments/assets/08a0b06c-7201-4ddf-8acd-b0969680bbef)

With migration of our blog from Medium to our website is necessary to change wording to:

"Read more on our blog" + change the redirection path to https://vexl.it/blog from https://blog.vexl.it/ This has to wait for my/Lea approval once every path will be redirected correctly. 

With that please change "Follow us on Twitter" to "Follow us on X" and change both icons. One for X's icon and for blog section I would add our glasses or some of the Vexlák as the icon.

**Comment by kaladivo** [comment]
This is done but the icons are missing for now.
