### ISSUE TITLE
New Zealand - Location not found

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#1195]

**Comment by kaladivo** [comment]
Should be fixed. it was FE bug so new app version is needed to release.

There is also one other problem. The center of new zeland is not a location inside city, so when you select New Zeland the map shows location as "location not found". Not really sure how to solve this but when we require the offer location to be a city it's not possible to get the the city name when location points to the Sea.

![Image](https://github.com/user-attachments/assets/c8056db9-000b-4e1b-9d1e-abcdcde1c88d)

**Comment by leomira** [comment]
Ah, I understand. Let's ship it as it is.
