### ISSUE TITLE
Deleting the offer should not delete chats

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#120]
Currently, when user deletes the offer, all opened chats to this offer are removed automatically. The main use case for *not* removing the chats is that user is tempted to remove the offer after he managed contact with the vexlaks and he wants to remove the offer already so he's not receiving more and more requests for this.

Current behaviour is that after you remove the offer, you lose the contact to the person you wanted to deal with.

**Comment by leomira** [comment]
working on Android

**Comment by leomira** [comment]
should work on iOS too 🎉
