### ISSUE TITLE
New phone contact not shown in the app's contact list

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#126]
I added a contact to my phone's contact list but it never manifested to the app.

I restarted the app several times.

iPhone Xs, iOS 15.6.1
Pixel 3A, Android 12

**Comment by mpocuch** [comment]
@leomira was the new contact on the same version of app? (newest build v1.0.10 is not able to display offers in old format)

**Comment by leomira** [comment]
@mpocuch this has nothing to do with offers - this is from the time we haven't even had 1.0.10 released yet 
but I have to say this is the problem that only I encountered, this seems to be working fine for @slush0 and @prusnak 
just to explain again, the problem is following:
1. I save a new contact to a phonebook.
2. App does not see this new contact in the Contact management view - not even after several restarts.
