### ISSUE TITLE
Yadio links

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#1271]
link to information about Yadio from the BTC price & profile and how often it is updated
+ market that it is a live price (and how live)

**Comment by leomira** [comment]
yellow dot to BTC Price at the top of the screen

BTC Price popup: 
title: Live BTC Price
text: Vexl sources BTC price from Yadio.io. It is refreshed every 10-20 minutes. 
Learn more on Yadio.io/info.html 

Popup v profile:
title: BTC Exchange rate
text: Vexl sources BTC price from Yadio.io. It is refreshed every 10-20 minutes. 
Learn more on Yadio.io/info.html

**Comment by leomira** [comment]
@kaladivo can we make a small adjustments to the yellow point next to the BTC Price? 

Could we set up the same color as text (or opacity) and center it vertically in position to the price information? 🙏

**Comment by kaladivo** [comment]
So this: 
![Snímek obrazovky 2024-09-18 v 14 21 06](https://github.com/user-attachments/assets/b6a010f1-0c5e-4952-8162-61bbe8b584d7)

Instead of this: 
![Snímek obrazovky 2024-09-18 v 14 21 33](https://github.com/user-attachments/assets/84c4de32-02fe-44c8-a7c7-186f042c2c0e)
