### ISSUE TITLE
Steps in offer price range

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#13]
Currently there is granularity of 1 CZK/EUR/USD when setting the price range.

Better would be if there were steps: 1000 CZK, 50 EUR, 50 USD.

**Comment by ondrejhadrava** [comment]
I had the same thought. How about two inputs "from" and "to" for setting precise price range?

**Comment by prusnak** [comment]
> How about two inputs "from" and "to" for setting precise price range?

This is already implemented. Update is waiting to be approved in the AppStore.

**Comment by leomira** [comment]
shipped in 1.0.10
