### ISSUE TITLE
Simplify location that are shown in the location column

### ISSUE THREAD

**Issue by stepanborovka** [vexl-it/vexl#1301]
Hey,

would it be possible to even list your offer on the level of cities and not the districts? I would love to list my offer for example just in Prague and when I'm searching through the other offers sometimes it's inconvenient to see Vinohrady, Karlín even without Prague. Just my personal experience.

![IMG_4678](https://github.com/user-attachments/assets/cabf0676-7be5-41f2-b5d4-d10b9b1a7c53)
![IMG_4679](https://github.com/user-attachments/assets/db59a63c-0286-4dfd-b7e5-8d51ba2730fe)

**Comment by leomira** [comment]
This issue has two parts: 
1. marketplace - here I propose showing both the district and the city, i.e. Karlin, Prague; Mitte, Berlin. This will be also better for a full text search.
2. offer creation - with the solution I propose offer creation then can be kept the same as it is now

**Comment by kaladivo** [comment]
![Image](https://github.com/user-attachments/assets/88ff494f-a7dd-46b1-b6a8-20ead5e2df71)
How about this?

**Comment by kaladivo** [comment]
![Image](https://github.com/user-attachments/assets/21b46708-6d68-46bd-b541-05a802beb3ac)
