### ISSUE TITLE
Retrieving of common contacts takes forever

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#131]
On my installation (~770 vexlers), downloading common contacts (/api/v1/contacts/common) takes 12 seconds (2x ~6 sec requests). That's that waiting time *before* progress bar in offer reencryption even appear, in create offer.

I suppose there's something wrong on backend side, like missing indexes, ineffective query or ineffective work with database results.

**Comment by slush0** [comment]
Alternative explanation: This offer is from somebody else (however no common friends in f-of-f seems also broken). Then the request from Lea never appeared (even after I restarted the app).

**Comment by leomira** [comment]
seems to be working, on Pixel 3A with over 770 vexlers this takes now around ~2s now, closing this
