### ISSUE TITLE
Deleted offer in chat detail should be displayed more clearly

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#132]
![IMG_6A9C512140A9-1](https://github.com/vexl-it/vexl-next/assets/11568934/0216140d-9a94-4b8a-b980-b646727ae4a5)

**Comment by leomira** [comment]
Design: https://www.figma.com/file/wyegUA8byXpHymF5lXxnkq/Vexl-App-V2.0-UI?type=design&node-id=7560%3A56573&t=W1RFRi2ZsSzC2Sge-1

**Comment by leomira** [comment]
connected to #128

**Comment by kaladivo** [comment]
This won't happen with chats open after the update where offer is "frozen" when chat opens. I suggest closing this issue.
