### ISSUE TITLE
Keyboard in the way and can't view text

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#1322]
Can't see what you are writing in the chat or offer box on iOS as the keyboard is in the way. Would it be possible to scroll up so that you can see what you are typing. It's quite annoying. 
![IMG_0643](https://github.com/user-attachments/assets/7dcb37e2-5a1a-4ee8-96f6-dd3aa969153e)

**Comment by SamTremko** [comment]
@satsdisco you can scroll the view manually and you should be able to see the text you are typing, its possible to scroll it automatically but its quite complicated in this case

**Comment by satsdisco** [comment]
maybe its just my fingers, but it doesnt work for me :( I can only hide the keyboard or see that it covers the text box
