### ISSUE TITLE
New Metrics to Grafana

### ISSUE THREAD

**Issue by stepanborovka** [vexl-it/vexl#1323]
Dearest devs,

It would be so great if we can track some of the metrics to Grafana. Specifically I mean this ones:

- I would love to track users retrospectively. So overall users for a random period of time (hours) or daily/weekly/monthly/yearly.
- Users by countries -> same daily/weekly/monthly/yearly.
- Same with offers - overall offers for same periods - daily/weekly/monthly/yearly.
- Offers by countries -> same daily/weekly/monthly/yearly.
- Abandoned users - how many users log out/delete their account again for some of the time periods.

I think, that's all. If you can think of something relevant, for sure you can add it too.
Thanks

**Comment by kaladivo** [comment]
We are collecting those metrics since today. You will be able to access them from now forward. :). 

Will create Grafana view next week when we have some metrics

**Comment by leomira** [comment]
connected to #3

**Comment by leomira** [comment]
connected to #810
