### ISSUE TITLE
Move bar above the button

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#1329]
![Image](https://github.com/user-attachments/assets/a187601e-26e2-493f-aae6-5b5114c6e4d4)

**Comment by leomira** [comment]
@SamTremko 

In contact submission, bar was not moved 
![Image](https://github.com/user-attachments/assets/930ce93c-14d9-496f-8a16-d05b50aecf96)

In request, it is rather flying - I propose adding it directly above the button or bottom of the screen if button is not visible
![Image](https://github.com/user-attachments/assets/3818f1dd-b8db-4d9a-bfc8-0089cb71aa2b)

On Pixel 8, for whatever reason, bar is still up on the screen no matter I updated the app 🤯

**Comment by SamTremko** [comment]
@leomira  Sorry I maybe misunderstood the task and moved the bar only for request messaging screen on offers without location. Only there is the bar at the bottom 😁 I was thinking, that there is the problem, that it is covering the avatar.

**Comment by leomira** [comment]
ah sorry, could have written it better :D

**Comment by SamTremko** [comment]
I can move it globally though if this is still valid
