### ISSUE TITLE
Request on migrated offer seems broken

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#133]
I'm on 1.0.10, Lea on 1.0.11, she requested my offer migrated from 1.0.9. The request is displayed without common friends, missing request message and accepting the request opens the chat which Lea don't see and cannot write in.
![Screenshot_20221027-191320_Vexl](https://user-images.githubusercontent.com/565341/198365692-4030d306-8512-457c-a0cb-5320b6a01b24.jpg)

**Comment by leomira** [comment]
seems to be fixed
