### ISSUE TITLE
Profile screen cannot be displayed

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#134]
In 1.0.10, somehow I got into the state where click to Profile doesn't display profile page, but keep displaying Marketplace instead. Clicking to Marketplace icon also select Profile page, but Marketplace screen is displayed. See attached screenshot and market Profile button.

Application restart helped.

![Screenshot_20221027_184442](https://user-images.githubusercontent.com/565341/198366492-1ba406ad-c24e-4f07-bbc9-f66ebbd2ad91.jpg)

**Comment by leomira** [comment]
should be fixed
