### ISSUE TITLE
Small bug in the chat

### ISSUE THREAD

**Issue by stepanborovka** [vexl-it/vexl#1392]
Hey, 

one small bug from support. Czech description:

Ahoj, po každé aktualizaci se mi u některých už dávno ukončených konverzací
ukazuje 'nepřečtený' puntík. To je bug nebo fíčura? Už je to tak asi půl roku, možná dýl.

![7D965503-7751-4CA6-BE89-8663ED7BBC46](https://github.com/user-attachments/assets/2e1dea6d-7b42-4a08-976d-1b5efc344828)

**Comment by leomira** [comment]
adding this to the todo, it happens mostly after the update of the app, would be nice to fix this
