### ISSUE TITLE
"Filter offers" button slightly changes position when switching between "Buying" and "Selling" tabs

### ISSUE THREAD

**Issue by ondrejhadrava** [vexl-it/vexl#14]
**Operating system:** iOS (latest)
**Device:** iPhone SE 2020
**App version**: N/A

**Screengrab**:

https://user-images.githubusercontent.com/44087609/190852165-125ed5d9-a6d3-438a-8d56-c2d951187b80.MP4

**Comment by adamusel** [comment]
Marked in JIRA ✅

**Comment by leomira** [comment]
shipped with 1.0.10
