### ISSUE TITLE
can't delete old chat

### ISSUE THREAD

**Issue by zaplmi** [vexl-it/vexl#141]
I can't seem to be able to delete old chat, that has been created before the most recent update (1.0.15)
It gives me following error:

![image](https://user-images.githubusercontent.com/91535734/201280034-19f254bf-963c-42bf-b848-f53c619ca980.png)

Then the app freezes and has to be restarted.

1.0.15-344-iOS 15.7

**Comment by leomira** [comment]
the same issue as #3 ? we expected it to be fixed with implementation of #120 @mpocuch

**Comment by mpocuch** [comment]
in https://github.com/vexl-it/vexl/issues/120 we were decoupling offers and chats, not solving this issue. so yes, it is still valid - #3  was never planned into any release and moved to ready status from our side

**Comment by leomira** [comment]
shipped in 1.0.18
