### ISSUE TITLE
Progress bar when creating new offer is not working 

### ISSUE THREAD

**Issue by zaplmi** [vexl-it/vexl#142]
After the recent update (1.10.15), when creating new offer the progress bar does not work as expected:
It shows 0% done throughout the whole time until the order is created:

https://user-images.githubusercontent.com/91535734/201287605-9e25fc21-3be7-492a-884d-a1e4cdb32aa4.MP4

1.0.15-344-iOS 15.7

**Comment by prusnak** [comment]
I have the same issue with iOS 16

**Comment by leomira** [comment]
shipped in 1.0.16
