### ISSUE TITLE
Vratte mi prachy prosim !!

### ISSUE THREAD

**Issue by daleto999** [vexl-it/vexl#146]
V aplikaci jsem si rozjednal vexl, poslal peníze a protistrana zmizela! Chápu, že vy je nemáte, ale přišel jsem o 10 tisíc. Případ plánuji nahlásit policii, ale ti s tím asi nic neudělají. muzu vam zaslat nejaké informace, abyste mi pomohli nebo mi to proplatili?

**Comment by prusnak** [comment]
Dobrý den,
V prvé řadě bychom rádi uvedli, že Vexl není směnárna ani burza. Vexl je peer-to-peer komunikační platforma, s pomocí které mohou uživatelé napřímo směňovat bitcoin.  Společnost vyvíjející aplikaci Vexl do transakce mezi uživateli nijak nevstupuje a není zprostředkovatelem směny. Uživatelé jsou v aplikaci Vexl propojeni pomocí zašifrované sociální sítě, vidí nabídky pouze přímých přátel a přátel druhého řádu (přátelů přátel u kterých se v aplikaci ukazuje seznam společných přátel). 

Uživatelé na platformě vystupují pod náhodně generovanými pseudonymy, v případě oboustranného zájmu si uživatelé mohou sdělit bližší detaily. Firma vyvíjející aplikaci Vexl identitu uživatelů nezná. 

Podobné podvody, jaké popisujete, nejsou v online prostředí ničím novým. Výhodou Vexlu je, že narozdíl od jiných platforem, kde dochází k podobným incidentům, v naší aplikaci si uživatelé mohou před odesláním bitcoinu oveřit identitu protistrany - například kontaktováním společného přítele.

Víc info a jaké zásady dodržovat tady: https://blog.vexl.it/ako-na-peer-to-peer-trade-vo-vexli-b2434dbc8907

**Comment by daleto999** [comment]
Děkuji za odpověď a mrzí mě můj původní rozčilený dotaz. Rozumím, jak vexl funguje, rozumím, že jste se mnou nevyjebali, jen to umoznili. Mám za sebou několik úspěšných obchodu přes vexlovací skupiny. Tenhle problém jsem nikdy neměl, jak je možné, že všichni mají anonymní profily a není způsob jak dohledat podvodníky? Jak to může být sociální síť, to už raději budu vexlovat přes facebook, kde je mnohem snadné si ověřit profil...

**Comment by leomira** [comment]
Vexl cti sukromie pouzivatelov a nezbiera ziadne uzivatelske data. Zodpovednost za verifikaciu je preto vzdy na ich strane.

Vyuzivame takzvanu siet maleho sveta - moznost verifikovat protistranu ma uzivatel vzdy, a to prave diky zobrazenemu zoznamu spolocnych znamych, ktoremu mozte zavolat. 

Mrzi nas, ze ste tuto moznost nevyuzili. Ked ste ziadnych relevantnych spolocnych znamych v aplikacii nevideli, jedna sa o inherentne riskantnu transakciu. 
Pre buduce pripady doporucujeme riadit sa blogom, ktory je nalinkovany vyssie.
Z nasej strany do aplikacie pridame v buducich updatoch warning pre mod online platby a casom ju planujeme zrusit uplne. 
Uvedomujeme si, ze sa jedna o sofistikovany podvod a podobnych pripadov moze s rastom aplikacie pribudat.
