### ISSUE TITLE
Signed-out user can still receive notifications /czech/

### ISSUE THREAD

**Issue by mpocuch** [vexl-it/vexl#149]
Pri odhlaseni uzivatele mazeme vsechny jeho offers, na zaklade toho v drivejsich verzich zmizely chaty u protistran a nebylo mozne odhlasenemu uzivateli psat.
V nove app chaty u protistrany zustavaji i po smazani offer, takze protistrana muze psat i odhlasenemu uzivateli. Ktery ale nema jak si tyto zpravy precist, protoze jeho private klice uz neexistuji. A tak se mu zobrazi push notifikace, po kliknutí na kterou se nic neděje. Taky se objeví error msg v appce "Neoprávněná chyba. Byl jsi odhlášen." (samozrejme s predpokladem ze dany uzivatel ma stale nainstalovanou appku)

Reseni: pri odhlaseni uzivatele zaroven poslat na vsechny jeho chaty DELETE_CHAT zpravu. A potom smazat vsechny uzivatelovy inboxy z BE.
Potrebujeme k tomu vytvorit/upravit 2 EP na BE. A pak je treba upravit obe FE appky, aby tyhle EP pouzivaly atd.

**Comment by leomira** [comment]
shipped in 1.0.18

**Comment by leomira** [comment]
shipped in 1.0.18
