### ISSUE TITLE
Import of numbers without prefix is not working correctly

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#155]
When a number in a standard slovak format is saved to the phone (09XX XXX XXX), the app does not show it in the list of contacts for import.

App should detect this number, add the same prefix as the registered one had and offer it in the list in the contact management section.

**Comment by prusnak** [comment]
This is tricky because some local numbers have extra zero (e.g. Slovakia) and others don't (e.g. Czechia). So for countries that have the extra zero se need to trim it.

**Comment by leomira** [comment]
True, also it was noted in our request for the original implementation.

**Comment by leomira** [comment]
should be working!
