### ISSUE TITLE
text overflow during onboarding 

### ISSUE THREAD

**Issue by zaplmi** [vexl-it/vexl#156]
During the onboarding process, in step where user have to agree with terms and conditions, text overflows and toggle button is not really visible.

os: iOS
app version: 1.0.6

![58BEC892-6A3B-4F92-975C-E3665180D987_1_102_o](https://github.com/vexl-it/vexl-next/assets/91535734/5ede6bf3-e6ae-4a2c-8f65-0b01479f7cf8)

**Comment by kaladivo** [comment]
Fixed in latest version
