### ISSUE TITLE
Offer not found

### ISSUE THREAD

**Issue by Petr-Mi** [vexl-it/vexl#156]
After start application I get error "Offer not found" on bottom of screen. And I cannot update my offer after this. I update text of offer a save it. Waiting for encryption. Done. But screen with "Done! Offer sent." is still showing. I was waiting long time - about 20 minutes. And I must restart application bacause app is frozen. 

Wexl 1.0.21, Android 13

**Comment by leomira** [comment]
Is this still happening?

**Comment by Petr-Mi** [comment]
> Is this still occuring?

Unfortunately yes :-(

**Comment by leomira** [comment]
fixed
