### ISSUE TITLE
Unilateral identity disclosure

### ISSUE THREAD

**Issue by hynek-jina** [vexl-it/vexl#161]
Steps to reproduce
- I accidentally refused to reveal my identity
- Requested it again
- We both has confirmed
- The peer saw my name and picture but i din't see his

![IMG_2804](https://user-images.githubusercontent.com/26002916/234822939-50dbbf2c-e79f-47a4-a696-5c71a8b0c217.PNG)

**Comment by leomira** [comment]
cannot reproduce
