### ISSUE TITLE
Error accepting request

### ISSUE THREAD

**Issue by Petr-Mi** [vexl-it/vexl#162]
When I try to accept the request, I get this error message. It's only for one request. The following request was received successfully. It looks like the applicant has removed their request.

![Screenshot_20230525_120049_Vexl.jpg](https://github.com/vexl-it/vexl/assets/81816858/87bd6bc0-2e92-45e2-bd60-e724da985f39)

**Comment by leomira** [comment]
resolved in Vexl 2.0
