### ISSUE TITLE
Include predefined content when opening ticket from the app

### ISSUE THREAD

**Issue by zaplmi** [vexl-it/vexl#168]
When opening the ticket directly from the app (**report issue** button),  it would be great to include predefined content, containing desired metadata such as:

- app version 
- operating system 
- os version 

(see picture below from current Vexl production build) 

![6C57AB93-C0B8-4D99-ACB4-1DD3AD5DAFD9_1_201_a](https://github.com/vexl-it/vexl-next/assets/91535734/538dfaeb-cdb8-41d0-bad1-14c2751c87da)

Currently, this is implemented only on iOS, please add support for both supports. 

Motivation: 
It really helps and speed up troubleshooting process and issue reporting, also it helps to scale better in case of increased support requests. 

In the future these kind of metadata can be provided via API call (and appear directly as a ticket custom fields in help-desk)

**Comment by kaladivo** [comment]
To show in mail: 
- Platform
- Version of the app
- Version of the system
