### ISSUE TITLE
UI: Improve readability and contrast

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#17]
- [x] Layouts Create offer / Edit offer / Filter are "black on black", UI needs more contrast
- [x] Buttons and links have different styles and colors, it's hard to guess what's clickable or disabled (Edit offer, New offer in New offer layout or My offers / Request in Sell/Buy tabs)
- [x] Its hard to guess if some option is selected or unselected, active field is only a bit lighter. In Payment methods in Edit offer, when all methods are selected or unselected, you actually don't know if they are selected or unselected. The same in Lightning/On-chain selectbox etc.

**Comment by leomira** [comment]
this we already address in #25 , if we approve these designs, I would reuse them for other parts of the app (filters, edit offer and so on)

**Comment by leomira** [comment]
The new, improved contrast from #25 was mirrored everywhere in the design file that will serve for the development of Vexl 2.0, hence I consider this to be done and close the issue.
