### ISSUE TITLE
Requested offer card not turning grey

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#178]
after an offer is requested, it should be turned grey (like in the old app) 

![signal-2023-06-02-144216](https://github.com/vexl-it/vexl-next/assets/25779015/94121719-6a00-4fb0-8584-bf111c2fd8ac)

**Comment by kaladivo** [comment]
@SamTremko this is one liner, that's why the reassigning

**Comment by leomira** [comment]
working well!
