### ISSUE TITLE
Requested offer not being sorted to the end of the list

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#179]
Instead of being moved to the end of the list, requested offer hangs in the same place on the marketplace. 
![signal-2023-06-02-144216](https://github.com/vexl-it/vexl-next/assets/25779015/47049785-3da9-413f-b8d6-c2ace09ed494)

**Comment by kaladivo** [comment]
This was not in the design at all

**Comment by leomira** [comment]
works like that in the old app, also, the grey color: 

https://www.figma.com/file/wyegUA8byXpHymF5lXxnkq/Vexl-App-V2.0-UI?type=design&node-id=7853%3A64738&t=2S3XNEn2KMJNSUYd-1

**Comment by leomira** [comment]
work well!
