### ISSUE TITLE
Offer in a requested state - Detail - Text update needed

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#180]
In a requested offer, I should see updated text according to state of the offer. 
Rn, I see "You've requested a trade. We'll notify you once it's accepted."

It should say either
"Your request was accepted." or "Your request was declined." 
at least until we implement offer TTL.

**Comment by kaladivo** [comment]
Ok, so it should say either: 
`You've requested a trade. We'll notify you once it's accepted.` - when no response was received yet
`Your request was accepted.` - when other side accepted
`Your request was declined.` - when other side denied

**Comment by leomira** [comment]
exactly. 

to avoid confusion, I add a screenshot, so you know exactly which text I mean. 
![signal-2023-06-02-141312_004](https://github.com/vexl-it/vexl-next/assets/25779015/c84c9dcb-463f-40c5-8961-1c82d9a838a8)

**Comment by kaladivo** [comment]
It would make sense to change this button also (based on the request status) to say `requested` `denied` `request accepted`. 

Does it make sense to you to change this?  

![Snímek obrazovky 2023-06-02 v 8 40 56](https://github.com/vexl-it/vexl-next/assets/11568934/a7c99764-9667-4ca8-b1cd-c95ec2e64433)

**Comment by kaladivo** [comment]
It would make sense to change this button also (based on the request status) to say `requested` `denied` or `request accepted`.

Does it make sense to you to change this?
![IMG_B99AAB56AA36-1](https://github.com/vexl-it/vexl-next/assets/11568934/027d53f1-8516-4026-b9d9-a84c80e28913)

**Comment by leomira** [comment]
it actually does, at least something until we have the offer TTL. 🤝
