### ISSUE TITLE
Offers not being loaded properly

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#182]
I installed the app, imported contacts (reach over 1K), but I see only very limited amount of offers on the marketplace (2 buy, 5 sell) even after an hour. 
This worked much faster (and in the background) in the old app.

**Comment by kaladivo** [comment]
The logic behind this was not changed. This is about issuing notifications and other devices processing them. We can try to fix this.

**Comment by leomira** [comment]
I can confirm that it seems to be much faster now!
