### ISSUE TITLE
Slider in create offer not functioning properly

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#183]
See attached printscreen. 
When I enter the price range manually, slider does not reflect the accurate state according to price.

![signal-2023-06-02-141312_007](https://github.com/vexl-it/vexl-next/assets/25779015/02920018-e137-4af9-acee-b21284d5fda2)

**Comment by kaladivo** [comment]
You mean the yellow bar not the buttons, right?

**Comment by leomira** [comment]
@kaladivo exactly, sorry for the misunderstanding. 
When I update the inputs, the yellow bar is not reacting properly.
