### ISSUE TITLE
Avatar being shown on the marketplace after reveal identity

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#185]
We show avatar after the reveal identity. This should not happen, we should keep the old, randomly generated avatar with the offer. 
Name works fine - stays the same. 

![signal-2023-06-02-144216_002](https://github.com/vexl-it/vexl-next/assets/25779015/779957c5-b4ad-4c69-963c-80451292015b)

**Comment by kaladivo** [comment]
Please add product explanation. Avatar is added to offer with which identity reveal happened.

**Comment by leomira** [comment]
It is inconsistent from the design perspective. Also, it seems to be buggy. If the above is true, why do you reveal the avatar and dont reveal name?

**Comment by kaladivo** [comment]
The second thing is a bug. Name should change too. Sorry for that. 

In this case, I would argue that it is more consistent to show images (and names) of revealed users on the offer list. This way we are giving user info about the offer that he/she knows. It makes it easier for user to navigate in the list. But I might be missing something.

**Comment by leomira** [comment]
As agreed via slack, let's reveal both - the name and the avatar.
