### ISSUE TITLE
Do not show "fetching your contacts from the server"

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#186]
This should not be there. Is it enough to just delete it from the translation file or do we need to fix it in the code? 
![signal-2023-06-02-150423](https://github.com/vexl-it/vexl-next/assets/25779015/0a990438-4b5a-4336-91f9-0322512029fd)

**Comment by kaladivo** [comment]
Why not? It's whats happening?

**Comment by kaladivo** [comment]
How about translate this to: 
`Fetching your connections from the server?`
