### ISSUE TITLE
Add social media contacts to the app

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#19]
* Twitter
* Blog

**Comment by slush0** [comment]
I would consider only bi-directional following as a real contact.

**Comment by prusnak** [comment]
I didn't mean for contacts, just to have links to twitter.com/vexl and blog.vexl.it somewhere in the app.

**Comment by slush0** [comment]
Ok sorry, deleted my comment.

**Comment by mpocuch** [comment]
@leomira in design is also medium - do we want to have it there? if so, please send the link where to redirect

**Comment by leomira** [comment]
shipped in 1.0.10
