### ISSUE TITLE
Search by location name does not work

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#192]
search by lat long instead

**Comment by prusnak** [comment]
I checked the formula in https://github.com/vexl-it/vexl-next/commit/327625fc1831102b1a449c3f05a94471b367eb29 and it seems correct providing that latitude and longitude are always given as strings that represent decimal values in degrees - i.e `"-50.073658"` and not `"50° 4' 25.1688'' S"` - is that always the case? I suppose so, but I am just checking to be 100% sure
