### ISSUE TITLE
Remove offers that are no longer existing

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#21]
It seems to me that the non-existing offers are not always removed from the app leading to bugs like these:

![Fc1tPxrWYAAHetn](https://user-images.githubusercontent.com/42201/190853741-6668b7e4-8d55-438d-b1a6-09cda10d7f39.jpeg)

**Comment by adamusel** [comment]
Marked in JIRA ✅

**Comment by leomira** [comment]
can't replicate anymore

**Comment by zaplmi** [comment]
One user has reported to Support that this issue still persists on 1.0.21-371 - iPhone - 16.1.1
