### ISSUE TITLE
Automatic re-encryption of offers

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#22]
There should be a way how to notify my phone when a new person enters my social network.

Once this notification is received, my phone goes over my active offers, re-encrypt it for a new person and upload it to a server.

This approach has limitation that iOS and Android limit the time for notification handling which is somewhere between 20 and 30 seconds. Ideally, we should be sending another notification when we are over this limit and we need more time to finish.

**Comment by slush0** [comment]
Is there any limit on number of notifications the phone can receive? -> Is there any threat that notifications will be throttled/skipped for some high profile contact then?

If there's slight chance that we cannot implement this robustly, there should be some failback solution to check for new offers, like once-a-day wakeup of the app and polling of the server. We will need such failback for devices without notifications (Graphene etc) anyway.

**Comment by slush0** [comment]
The conclusion after discussion with the team is that phone will try to re-encrypt the offer for new user right after receiving the silent notification, and if it will fail to finalize within given time period (there's limitation how much processing time the silent notification can take), it will be performed when the app is open in foreground.

**Comment by mpocuch** [comment]
dev estimates: 3 MDs / platform; ETA for delivery: 27.9. EOD
