### ISSUE TITLE
Chat cannot be deleted after requested offer is deleted

### ISSUE THREAD

**Issue by SamTremko** [vexl-it/vexl#228]
Steps to reproduce:

1. User A creates offer
2. User B Requests the offer and writes a message to user A
3. User A deletes the offer
4. User B sees the chat, cannot write to it nor can delete it

![image](https://github.com/vexl-it/vexl-next/assets/32439382/2fdbdbd5-4883-4252-9583-5f0565931120)

![image](https://github.com/vexl-it/vexl-next/assets/32439382/44b294ad-e360-4fad-95b9-f2569605199e)

**Comment by leomira** [comment]
fixed now
