### ISSUE TITLE
Empty marketplace: more explanation

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#23]
When there are no offers in the marketplace we should offer an explanation and suggest a user to add more contacts and more offers and wait ...

**Comment by jkuchar** [comment]
1. Maybe also show how (approx) many people in social graph uses vexl? It would help get a feedback, that the app is actually useful even though there are not offers at the time.
2. Suggest to post an offer. Even when they do not see anything, they can have people in reach.

**Comment by leomira** [comment]
fixed in Vexl 2.0
