### ISSUE TITLE
Select text in chat

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#237]
Allow user to select and copy chat message

**Comment by kaladivo** [comment]
Just making Text element `selectable` does not work, because it is inside of the scroll view. So the touches are registered by the scroll View and not the text element. 


Maybe putting the text inside the Input element would work, but then there might be a performance issues. 

The best approach might be to just long press and display _copy_ popup

**Comment by prusnak** [comment]
Alternative approach:
- add detection for bitcoin addresses and lightning invoices
- make them clickable and when user clicks on them, the content is copied into clipboard (with shortly shown popup info that the content has been copied)

Patterns:
- [13][0-9a-zA-Z]+
- bc1[0-9a-z]+
- BC1[0-9A-Z]+
- lnbc1[0-9a-z]+
- LNBC1[0-9A-Z]+
- lnurl1[0-9a-z]+
- LNURL1[0-9A-Z]+
- email-like (user@host.com) lnaddress
