### ISSUE TITLE
Create offer needs some love

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#25]
- [x] In general fields are missing any description.
- [x] It is not clear what people should write into Description field. Basically explain that Description is a sales pitch why people should take your offer.
- [x] Description being the first field is not practical; people don't see what they'll fill up later in the form. Put Description to the bottom of the form, so they already know what's defined.
- [x] It's unclear how to deactivate / delete Price triggers. The section is opened by default (as advanced feature this should be closed by default) and "delete" button does not seems to do anything.
- [x] Online and In person should not be a checkboxes, but radio buttons (one or another)
- [x] In "Online only", location has no meaning and should not be allowed to fill in.
- [x] In Location, "+ Another location" is confusing, when there's not any Location entered yet (it should be "Add location" maybe, or by default there should be one location field opened already?)
- [ ] Location prompt is completely confusing. "Praha 7, Slovensko" - really?
- [ ] The form is missing any settings for the bitcoin price and people are actually confused why the form is not asking for what price they want to buy/sell. That's related to following issues:
- [x] With fee / without fee - Based on feedback, people don't get the fees section. Comparing to what the fee is charged (spot price).
- [x] Currently, the fee cannot be negative (I'm offering fee for taking my offer).
- [x] UI needs to be better arranged to several clear sections, or even several pages. It is already a long page and with all the explanations it will be even worse.
- [x] Price trigger sticks with currency set up in the Profile. It should reflect selected currency of the offer instead.

**Comment by leomira** [comment]
I am linking this for an inspiration: https://github.com/vexl-it/vexl/issues/100

**Comment by slush0** [comment]
Additionally, also #82 is relevant.

**Comment by leomira** [comment]
Most of this was shipped in Vexl 2.0.
Location whisperer deserves a separate issue.
