### ISSUE TITLE
Localization of Privacy policy & Terms of use

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#257]
Currently we have only cz and en translation

**Comment by leomira** [comment]
WIP
- SK
- FR
- DE
- IT
- SP

**Comment by kaladivo** [comment]
Add Portuguese also

**Comment by leomira** [comment]
@SamTremko this is the issue I was speaking about

let's use DeepL translations, just with an alert for the users that it is a machine translation + redirect to the official one (english)
