### ISSUE TITLE
Explain importance of notifications

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#26]
Currently on iOS, the request for notifications appears without any explanation in warning, and users automatically deny them (saw them on my eyes). It is important to explain the importance of notifications before requesting the permission.

**Comment by slush0** [comment]
I propose one specific solution which I saw in some other application:

1. Show screen informing about necessity of having notifications enabled.
2. Instead of button, show checkbox/slider "Enable notifications", which triggers system popup for enabling notifications

This is IMO better solution than having "Yes/Confirm/Next" button as the slider reminds more an agreement with some terms and indicates that it is necessary to perform to move forward.

**Comment by mpocuch** [comment]
@slush0 in progress (without the slider feature for now - for a faster delivery). If you want to keep the slider idea, I propose to raise it as a new ticket (with lower prio)

**Comment by slush0** [comment]
Since Android 13, we need the same mechanism even for Android.

**Comment by leomira** [comment]
It is already planned to be rolled out for both, it was just a label missing.

**Comment by leomira** [comment]
@mpocuch I just tried this on a new login (Android 12) - The screen was not shown and I was not prompted to allow notifications. Is this implemented only for Android 13?

**Comment by mpocuch** [comment]
yes, only for AN13 - lower versions do not require the permission to be prompted

**Comment by leomira** [comment]
alright
