### ISSUE TITLE
Filter is not being reset after closing

### ISSUE THREAD

**Issue by SamTremko** [vexl-it/vexl#264]
Steps to reproduce:

1. Open filter
2. Change any value
3. Close filter
4. Open filter (the value that was previously set is still there)

**Comment by leomira** [comment]
I am not sure if I understand what the bug here - once set filter should be remembered, check #304 and the relevant discussion 🙏

**Comment by SamTremko** [comment]
This is ment like, when u enter filter screen and do some changes, then you close it without applying (saving) and you come back, you can see the previously set values

**Comment by SamTremko** [comment]
The discussion in #304 is about logic after applying or saving filter. I think fields in filter should be reset if user comes back to it without previously applying anything

**Comment by leomira** [comment]
Ah, alright! Now I get it, makes total sense. 
 But good that we noticed we already have #304 open, it has rising priority given the amount of the offers on the marketplace (and their geographical variety)
