### ISSUE TITLE
Design and translate NotificationPermissionsScreen

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#268]
Notification permissions screen is displayed on every focus when user did not allow notifications to vexl. Currently the screen looks really bad and is not translated.

**Comment by leomira** [comment]
The design: https://www.figma.com/file/wyegUA8byXpHymF5lXxnkq/Vexl-App-V2.0-UI?type=design&node-id=6539%3A37045&t=xBA27hQrXlwjGXou-1

**Comment by leomira** [comment]
I would add a translation ASAP, but I can't find it in the localization file.

**Comment by leomira** [comment]
seems to be working now, however still no translation input.
