### ISSUE TITLE
Add a total count of offers on the top of marketplace 

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#272]
Let's add a total number of offers per buy and sell marketplace. 

As a user, I want to know immediately how many offers I have to chose from. Currently, we have no such information shown anywhere in the app.

**Comment by kaladivo** [comment]
We need to find a proper place for where to display the number. I don't think designer is necessary in this case. But this needs to be clear before we can start implementing such feature.

**Comment by leomira** [comment]
No need to overthinkg this, a simple 
[Total: N offers]() would make it.![Screenshot_20230614-111605~2.png](https://github.com/vexl-it/vexl/assets/25779015/c10560e1-ab8f-4b35-b35c-f0212272299a)

**Comment by leomira** [comment]
@SamTremko  After the discussion today, let's correct the view of "total" to the bottom of the marketplace and find a way how to communicate a number of filtered offers (in the button?)

**Comment by prusnak** [comment]
my suggestions:
- use the space above like right now but make it scrollable (so it disappears when I scroll down and doesn't eat the screen estate)
- let's left align the text (now it is right aligned)
- if filter is inactive use this string: `Total: X offers`
- if filter is active use this string: `Filtered: Y offers (out of total X)`

**Comment by leomira** [comment]
Also works for me ✔️ It is less elegant solution but if it is easier to be shipped I think it is alright. 
I would change the color of the string to white though, so it is less dominant in the UX.

**Comment by SamTremko** [comment]
So I implemented the thing this way:

- I changed the colour to grey to not take that much attention on board
- the element scrolls away with offers
- in case user has e.g. 5 offers its displayed like this:
![image](https://github.com/vexl-it/vexl/assets/32439382/9b3b2a3c-1443-4272-8b0d-54c9b48e113d)

- in case filter is active and some offers are still visible:
Here I would point out wht number should be displayed, as word **Filtered:** seems to me like we want to either display how many offers are filtered out of total, or how many are left on marketplace screen out of total?
![image](https://github.com/vexl-it/vexl/assets/32439382/1b83dd0b-9981-4848-8da5-d89d6598ed3d)

- in this case filter is active and no offers are on marketplace (element is hidden as it has no sense for me here, only info about filter being to specific is displayed):
![image](https://github.com/vexl-it/vexl/assets/32439382/c0a83fde-16fb-4d71-a77c-cf04f7ec1343)

**Comment by leomira** [comment]
In my opinion, this works great (particularly with the combination of the "empty markeplace screen" with the same CTA)! 
As for "Filtered" - if I understand the question correctly, we want to show the amount of offers that left on the marketplace after applying the filter.

**Comment by leomira** [comment]
@prusnak how do you like this?

**Comment by leomira** [comment]
@SamTremko can you pls also show how does it look like once the vekslak dialog is closed?

**Comment by SamTremko** [comment]
Yeah sure:
![image](https://github.com/vexl-it/vexl/assets/32439382/36a9e124-fe54-40f1-a88d-15bdc06c2408)

**Comment by leomira** [comment]
great, done! 🎉
