### ISSUE TITLE
Allow users to report/flag the offer directly from the chat. 

### ISSUE THREAD

**Issue by zaplmi** [vexl-it/vexl#274]
It would be grate if user could report/flag the offer directly from the chat after being connected with the counterparty (after realising or experiencing that the offer/user who posted it is shady or scammy). 

The offer in the marketplace gets greyed out and such option is not available. 

Currently, the only option is just to block the user in the chat.

**Comment by leomira** [comment]
Makes total sense and actually this is a really easy from a UX perspective with the current UI, would just add it here, below "Reveal identity" and a flag button next to block button on the top:
![signal-2023-06-13-220644](https://github.com/vexl-it/vexl/assets/25779015/e390defd-298b-4fe9-b9b5-3cb9f3a53baf)

**Comment by SamTremko** [comment]
@leomira I implemented it like this:


![Image](https://github.com/vexl-it/vexl/assets/32439382/a570af9a-b004-4494-a268-f5be896ea3a8)

and if offer was already reported and chat is still available

![Image](https://github.com/vexl-it/vexl/assets/32439382/31fdf5dc-c845-4f65-b591-313b7565c48a)

**Comment by leomira** [comment]
@SamTremko za mna parada!

**Comment by leomira** [comment]
@SamTremko works fine, just one small issue: when offer is reported via chat, the number of total amount of offers does not update on the marketplace

**Comment by leomira** [comment]
now it seems to be updating the total count!
