### ISSUE TITLE
Group QR codes 

### ISSUE THREAD

**Issue by vdovhanych** [vexl-it/vexl#276]
`contact-ms` now stores group QR codes in static storage, and the app gets it through CDN. 
It would be nice to eliminate this behavior and use something similar to avatars. 
Perhaps: the `contact-ms` backend will write the group QR code as bas64 to the database, and the app will display it from that base64 returned in the API response.

Benefit: getting rid of persistent storage for our cluster and removing the CDN component altogether -> further simplifying our infrastructure.

**Comment by leomira** [comment]
this is irrelevant rn, closing this
froups will probably have completely different workflow than originally designed by Cleevio
