### ISSUE TITLE
Abnormal number of backend calls for common contacts

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#277]
In application log, I see spikes of traffic to /api/v1/contacts/common. It is tens of calls in sequence (I counted up to 30 requests *per second*) from my phone. This is mystery to me why this is necessary and it definitely looks unhealthy.

I'm not sure which component fire such number of requests, but I suppose it is marketplace, because the wall of requests starts with calls to bitcoin chart refresh. So my guess is some ineffectivity in listing of offers, where every offer fires its own request to backend.

This is observed on Android, it is unclear if ios has the same issue. @leomira would you try to replicate?

**Comment by leomira** [comment]
@slush0 would you be able to check this now, so we find out if it's still relevant?

**Comment by slush0** [comment]
It is very unlikely to be relevant in the vexl2. I briefly tested the scenario and I don't see any such behavior happening anymore. Let's close this.

**Comment by leomira** [comment]
Thx, closing!
