### ISSUE TITLE
Allow manual import of phone numbers

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#282]
Several people gave feedback that they don't maintain a contact list in the phone (for privacy reasons), but they wouldn't mind jotting the contacts down to the app and letting it to be stored in the app. 

This would be a nice improvemenet also for another use case - I could save someone's number directly to Vexl, without going through contacts and then import (i.e. I just met a 2nd degree contact for Vexl and I liked the trade)

**Comment by leomira** [comment]
We already implemented this offer in Vexl 2.0, but you can enter just a phone number. Would be great to be able to add a name as well @kaladivo

**Comment by kaladivo** [comment]
Closing this one, let's use #314 for adding name
