### ISSUE TITLE
Trade checklist

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#283]
In addition to trade calculator vexl-it/vexl-next#300, it would be **extremely** useful to have some guide or checklist in the chat to help reaching agreement on various topic of the deal. It can be very useful for inexperienced users to don't forget to something important, but it is also very useful for professional vexlers who are handling multiple deals at the same time, to not forget to something.

My idea is that any side of the trade can propose (enter) some trade detail and the other side would have a chance to confirm :heavy_check_mark: it. In the end, there'll be a list of trade details, confirmed by both sides even prior the physical meeting, so nothing has to be discussed on place, not only saving everybody's time, but also preventing misunderstandings and scams. 

Proposed fields of the form:

- Amount of fiat or BTC, fee and rate (this could be directly integrated to vexl-it/vexl-next#300, so users can freeze any values there or use spot prices at the meeting time)
- Coin or network (BTC, LN, ...)
- Buyer's (bitcoin) address (this could be clickable to some block explorer)
- Address/place of the meeting
- Date and time
- How to recognize themselves ("poznavaci znameni")
- Reveal identity

Additionally, if the amount and bitcoin address is filled, there could be a button to check transaction state. The use case is that receiving side can prepare the address in advance (Trezor at home) and is able to check if they received the coins already (not received, unconfirmed, confirmed states) directly in Vexl app.

**Comment by leomira** [comment]
would be nice to have this directly connected to #308 - this would one of a good places to collect feedback
