### ISSUE TITLE
Batch uploading by ~1000 offers to prevent backend issues

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#284]
Currently clients encrypt all offers and upload them to backend in a single call. This does not scale well and we can reach memory or CPU limits pretty easily. What's even worse that such errors are hard to debug and fix.

It's a good practice to don't let memory and CPU resources rise idefinitely, so I propose to limit ~1000 offers per single call. This would probably need some additional work and we have to handle corner cases like failing requests (not all offers will get successfully) and what to do with that.

**Comment by kaladivo** [comment]
related to #1202

**Comment by kaladivo** [comment]
Limit set to 100 for now. Can be tweaked with one constant.
