### ISSUE TITLE
Indicate spoken languages in the offer

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#286]
Currently people mix czech/slovak and english offers. Let's allow to specify in the offer, which languages the vexlak speaks. This could be a multi-entry field (similar to Location field), which can be later filtered out by other parties in marketplace.

Eventually this could be a settings in Profile and offers could inherit this settings automatically. UX is definitely needed here.

**Comment by leomira** [comment]
this also raises up in priorities given the international reach now.

**Comment by kaladivo** [comment]
What needs to be changed: 
- In every offer needs to be displayed language of the offer
  - Offer detail
  - Offer preview in marketplace
  - Offer preview in chat
- In form to create/update offer needs to be language picker
- In filter needs to be language field that user can filter by
- Specify language in offer request
- Communicate language specified in request when accepting request

Questions: 
- What should be the fallback language for offers created before this feature was added?
- Can only one language be added to offer or should there be an array of languages? - **array**
- Filtering using one value or array? - **array**
- What is the design for offer request (both sides)

**Comment by kaladivo** [comment]
**IDEA**
Language should be selected in onboarding. Later should be modifiable in the same way as name or profile picture.

- Question : what to do with existing users? What language should be default?

**Comment by kaladivo** [comment]
**IDEA**
Language should be specified when creating offer with default prefilled value of locale.

**Comment by kaladivo** [comment]
Create new offer settings is being cached and once user creates offer with language next time the form is displayed, it's displayed with the same preset

**Comment by leomira** [comment]
UX ready ✅

**Comment by leomira** [comment]
https://www.figma.com/file/UzjHcXPfNOOTVmcafQx4iP/Vexl-playground?type=design&node-id=0-1&mode=design&t=0UyFaoNdu9JDHfym-0

**Comment by leomira** [comment]
works just fine
