### ISSUE TITLE
It's not possible to display details of requested offer or delete it

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#292]
After requesting the offer, it is no longer possible to show details of the offer or even the message sent in the offer. It is also not possible to cancel&delete the request, which is a privacy issue (there's a proof that I requested the deal and I cannot remove it without uninstalling the app).

This is loosely related to vexl-it/vexl-next#311 and vexl-it/vexl-next#299 as set of improvements around Request offer feature.

**Comment by SamTremko** [comment]
Solved as part of [this issue](https://github.com/vexl-it/vexl/issues/263)
