### ISSUE TITLE
Avatar in Reveal identity is too tiny (and cannot be enlarged)

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#293]
Avatar in Reveal identity (and later in chat window) is too tiny and cannot be enlarged. That may be problem for some photos where the person is taken from distance, with bad lightning etc.

**Comment by kaladivo** [comment]
AC: 
- when user presses on reveal identity message's avatar it opens it in full screen view `
- There is close icon at the top right of the full screen view of the avatar
- When user presses back (on android) full avatar closes
