### ISSUE TITLE
Sort offers by a fee policy by default

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#294]
Currently, the offers in Marketplace are not sorted anyhow, because nobody would guess that this will be an issue too soon after launch ;-).

We cannot sort by geo location yet because vexl-it/vexl#73 is not implemented yet, but let's sort by fee policy (the most favorable fee for viewer first). This would be quite interesting after vexl-it/vexl#82 will be implemented.

**Comment by kaladivo** [comment]
@slush0 In 2.0 Default sort is LOWEST_FEE_FIRST. Can we close this?

**Comment by slush0** [comment]
Yes
