### ISSUE TITLE
Implement "reply to" messages in chat

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#295]
In complex discussion (discussing fees, location, identification, ...) it can be easy to get lost. Please implement "reply to" messages, so the new message refers to some previous one.

It can be triggered by right-swipe of chosen message, and display previous message grayed above the newly send message.

If unsure, get an inspiration in Signal. The implementation can be much more basic, though.

**Comment by leomira** [comment]
@kaladivo I tested this and it seems to be working well, the only thing - can we maybe change how to trigger the copy/reply UI? 
Now it is long press and I am afraid the users won't get it at all. If swipe is too complicated, maybe we could just simply change it to a short tap?
