### ISSUE TITLE
After deleting the chat, it is no longer possible to request the offer again

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#299]
Problem:

When I request the offer, the offer visually get stuck at "Requested" state. Later, when both sides close the deal and delete the chat (which is a good practice for privacy reasons), it is impossible to re-request the same offer again for making the deal with proven vexlak again.

Expected behaviour:

After chat is closed, the offer in Marketplace should reappear in basic state again, so it is possible to Request it again. The solution for situation where trade does not go well, there's Block contact already, so recuring contact should be possible without explicit blocking.

**Comment by SamTremko** [comment]
Solved as part of [this issue](https://github.com/vexl-it/vexl/issues/263)
