### ISSUE TITLE
Can't delete chat when offer is deleted

### ISSUE THREAD

**Issue by zaplmi** [vexl-it/vexl#3]
When trying to delete the chat after the deal is done,I get following error:

![image](https://user-images.githubusercontent.com/91535734/190395353-9e22b16f-99ce-4c13-b9c1-2f78995288d3.png)

Then it is possible only to click on X to exit the chat and it doesn't work either. 
The app freezes. 
I have to close it and reopen it.

Device: iPhone Xs Max 
Platform: iOS 15.6.1

**Comment by prusnak** [comment]
I think this is caused when the counterparty removes the offer, but somehow the app does not receive notification that the chat is already non existing.

**Comment by adamusel** [comment]
Marked in JIRA ✅

**Comment by leomira** [comment]
@adamusel what does the comment above mean please? I suppose it is some kind of integration message?

**Comment by leomira** [comment]
@zaplmi can you please check if is this issue still present? we've updated the app several times in the meantime, so if it does not persist I suggest to close this

**Comment by prusnak** [comment]
> can you please check if is this issue still present?

Yes, the issue still persists.

**Comment by leomira** [comment]
this seems to be working for me now, could you try out @prusnak or @zaplmi ?

**Comment by prusnak** [comment]
No, still not working on iOS with version 1.0.10

**Comment by slush0** [comment]
I suppose this could be fixed as a side effect in #120.

**Comment by leomira** [comment]
shipped in 1.0.15

**Comment by mpocuch** [comment]
in #120 we were decoupling offers and chats, not solving this issue. so yes, it is still valid - was never planned into any release and moved to ready status from our side
