### ISSUE TITLE
Change the way how chat message TTL is managed [czech]

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#301]
Zprávy se promazávají, pokud si je příjemce přečte. Chápu to tak, že pokud si je nepřečte (například odinstaloval appku, nemá notifikace, …), zůstávají zprávy v databázi viset. My nechceme držet data do nekonečna kvůli zodpovědnosti a forward security (v případě leaku šifrovacích klíčů z mobilu, …). Navrhuji přidat ke zprávám časové značky “created_at”, a hromadně promazávat dlouho (měsíc?) nepřečtené zprávy, které si aplikace z backendu nevyzvedla.

Navrhuji ukládat pouze datum DATE (a ne čas TIMESTAMP), kvůli zvýšení privacy uživatelů (z databáze nelze usuzovat časové usage patterny).

Pseudokód:

`ALTER TABLE message ADD COLUMN created_at DATE DEFAULT NOW()`

**Comment by kaladivo** [comment]
Pokud chceme úplně zamezit získávání nějakých časových paternů co prostě ke každé zprávě random vygenerovat čas, kdy se smaže. Něco jako 15-20 dní? A nebo už je to moc zbytečná komplikace? Z implementačního hlediska je to stejně easy, jako ukládat čas vytvoření...
