### ISSUE TITLE
Use notification badges (pending chat requests + unread chats)

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#303]
We can use the notification badges to show the following number = pending chat requests + unread chats with new messages

![image](https://user-images.githubusercontent.com/42201/190929503-94713b14-89e0-411b-83a6-8a8746b7f1ae.jpeg)

**Comment by kaladivo** [comment]
https://notifee.app/react-native/docs/ios/badges

**Comment by leomira** [comment]
works on Android

**Comment by leomira** [comment]
iOS working as well!
