### ISSUE TITLE
Remember filters

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#304]
After setting up a filter, it should be remembered by app when it is launched the next time.

**Comment by SamTremko** [comment]
I am refactoring filter a little, so it would be good to maybe merge my work and this one together.

So wht I understand:
- we want filter to be saved through app closing/opening
- we want filter to be the same for both buy/sell tabs, so once filter is applied to buy tab it is automatically applied to sell tab and also in oposite direction

**Comment by leomira** [comment]
Yes, exactly as you described.

But as a part of this, we also need to make it more clear that the filter is applied and have the option to reset it.

**Comment by SamTremko** [comment]
Ok I will figure it out and come up with solution for all the issues mentioned.
