### ISSUE TITLE
Improve notification handling

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#306]
Vexl notifications are obtrusive on Android. They don't display any useful information and they don't disappear when user visits the app/section. Proposed solutions:

- [ ] Would be awesome to show preview of the notification (I understand that this cannot be pushed from Backend, but Backend should fire silent notification to App, App should read the content and display enriched Notification to the phone).
- [ ] #466

**Comment by kaladivo** [comment]
Handled differently in 2.0. Closing

**Comment by kaladivo** [comment]
This issue is still relevant. Reopening.
