### ISSUE TITLE
Implement notification channels

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#307]
Implement notification channels, so users can better customize what kind of notifications they want to receive. Offering them customization gives users the way to disable invasive notifications yet allow application to work (as notifications are crucial for application to even work).

**Comment by kaladivo** [comment]
Currently there are following channels: 
- General notifications
- Chat related notifications
- Testing notifications - if user enables notifications from debug screen

Currently we don't send notification that would belong to any of the types you specified. 

I suggest closing this issue.

**Comment by leomira** [comment]
maybe let's keep this open, as it is connected to #280 and #302 ?

**Comment by leomira** [comment]
**current list of the notifications:** 
- Offer related (requested, approved, denied)
- Chat related (new message, identity revealed, identity request, chat deleted)
- Marketplace related (new offer)
- New offer per set filter
- New contact in the phone - not imported to vexl
- inactivity alert (your offer will be disabled)
- potential "marketing" notifications like "did you know that..."?

**Comment by kaladivo** [comment]
There are categories on ios in notifee library : https://notifee.app/react-native/docs/ios/categories
