### ISSUE TITLE
Rejected offers hangs in requested state forever

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#311]
Similarly to vexl-it/vexl-next#299 (which solves the problem with accepted and finalized deal), offer which is rejected hangs indefintely in the marketplace listing and bloats the listings.

It is unclear if it should be possible to re-request the deal at the some time in the future or the reject is dead end. Please note that the offer may be rejected for several momentary reasons like outstanding demand above the current vexlak capabilities. At this point it is desirable to give the user quick ability to reject the offer, but allow the requestor to retry later again. For permanent blocing there's Block contact feature instead.

Idea: After rejecting the offer, it should be visible in offer card, but with possibility to retry after some timeout (think of one day?)

**Comment by SamTremko** [comment]
Solved as part of [this issue](https://github.com/vexl-it/vexl/issues/263)
