### ISSUE TITLE
Rate limiting for Report offer feature

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#312]
Introduce rate limiting for the Report offer feature so I cannot report more than N=3 offers in T=5 minutes.

Let's make N a T easily configurable.

There are two approaches to this:
1. implement in the client (RN app)
2. implement in the backend (with easy to understand error message in the client).

I am leaning to 2. but since this needs a change in the database and API, maybe let's do this after we rewrite the offer service to TypeScript?

**Comment by leomira** [comment]
working well!
