### ISSUE TITLE
Consider using offline geocoder

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#313]
Such as https://github.com/lucaspiller/offline-geocoder

the code above builds the data from:
* cities above 1000 ppl: http://download.geonames.org/export/dump/cities1000.zip (~8MB compressed)
* administrative units: http://download.geonames.org/export/dump/admin1CodesASCII.txt
* countries: http://download.geonames.org/export/dump/countryInfo.txt

we can easily build our own dataset from these, for example:
```
city, administrative unit, country, population
```

and sort the returned answers by population

**Comment by leomira** [comment]
duplicate #256
