### ISSUE TITLE
When adding contact manually, allow user to set contact name

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#314]

**Comment by leomira** [comment]
would be great to have an opportunity to directly save it to the phone (checkbox)

**Comment by kaladivo** [comment]
AC: 
- when adding new contact using qrcode or deep link show input with predefined contact name as sent in payload but allow user to change it
- When adding custom contact using `add contact` in contact list, show modal and allow user to specify contact name

**Comment by leomira** [comment]
It works fine, I just found a bit of bugysek @SamTremko : 


![Image](https://github.com/vexl-it/vexl/assets/25779015/1effdf49-6eb7-467e-9e05-5a93dadfe5f8)

**Comment by SamTremko** [comment]
@leomira yes :/ I found it few minutes ago. Its my bad due to some miss-sync with translation table, its fixed in: https://github.com/vexl-it/vexl/pull/406

**Comment by leomira** [comment]
works well now!
