### ISSUE TITLE
Disallow screenshots 

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#316]

**Comment by kaladivo** [comment]
Let's not complicate this. See if there is a config flag for this and use that.

**Comment by leomira** [comment]
works fine 🎉

**Comment by SamTremko** [comment]
@leomira just to add, this will not work for iOS 17 version and above for now, as there are OS limitations to do this. The lib is not working 100% correct for that. On those version the functionality is hidden for the user

**Comment by leomira** [comment]
@SamTremko ok, pls open an issue regarding this particular scenario and version for the backlog, so we don't forget about it
