### ISSUE TITLE
Show progressbar when (re)encrypting offers

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#32]
Currently, dumb loader is displayed when the phone do heavyweight computations of encrypting offers for its social network. On big network or slow phone this can take significant time. With dumb loader it seems that the app is stuck and does nothing and it is unclear how long the process will take.

I propose to show progressbar with numbers of contacts the phone is encrypting to. As a side benefit, user will see how big his network actually is.

Maybe also warning that user should not send the app to background can be displayed (is this a thing? I suppose the app can be killed on background or at least the performance can be severely reduced)

**Comment by mpocuch** [comment]
ETA 27.9.

**Comment by leomira** [comment]
when I click on the screen (away from progressbar) I loose the progressbar and it is not possible to trigger it back. Also, the offer does not finish encrypting and the screen freezes. 

I have a screen recording available.
