### ISSUE TITLE
Currency pick in dropdown instead of select

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#320]
connected to #234 

The dropdown could look the same as the country code dropdown in the phone number verification, the format would be just more descriptive - flag, name, shortcut, i.e.:
🇭🇺 hungarian forint - HUF

**Comment by SamTremko** [comment]
@leomira do we have design for this one?

**Comment by leomira** [comment]
@SamTremko no design per se, as we wanted to reuse the one that we already have implemented in country code (in onboarding)

**Comment by SamTremko** [comment]
@leomira yeah right, I should remember: First read the description -> write comment after that, sry 😆

**Comment by prusnak** [comment]
PR https://github.com/vexl-it/vexl/pull/373 is prerequisite of this feature
