### ISSUE TITLE
Location & Map

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#322]
I aim to describe a rather more complex issue regarding the way how we use and work with location and potentially a map in the app. 

This penetrates three areas of the app: create offer form, marketplace and filters.

**Create offer:** 
The idea is that while creating an offer a user could drop a pin on the map that would create a radius (that might be also adjusted) of where the offer was posted. This way we could prevent mistyping the wrong location of the offer (i.e. Berlin in US, Berlin in Germany).

**Marketplace:** 
A user should be able to open a map view and browse offers on the map, then directly request them from the map.

**Filters:**
A user should be able to set a radius based on a map. Then he could be notified for new offers posted in this radius. 

1. good UX is necessary.
2. needs to be done in a privacy aware way.
3. this should always stay **offer centric**, NOT *user centric* - we wanna display location of the offer, it should not be connected to location/filter of the user by any means.
4. I like how Packeta works with the location, I attach an example.
5. Connected to #280 and #304 

https://github.com/vexl-it/vexl/assets/25779015/f44097bd-fd47-4dc5-970f-4264f1c95ead

**Comment by kaladivo** [comment]
Design here: https://www.figma.com/file/wyegUA8byXpHymF5lXxnkq/Vexl-App-V2.0-UI?type=design&node-id=9421-38229&mode=design&t=dm8g6fSR1VHpXWPO-4
