### ISSUE TITLE
Fee/Discount nomenclature bug

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#324]
[will add later]

**Comment by SamTremko** [comment]
It's true, currently we have there only 'For seller' in all offers if fee is present.

**Comment by leomira** [comment]
@SamTremko before we solve the nomenclature we need to fix the functionality. Lmk when you'll have the capacity, if you need some clarification I am ready to hop on a call.

**Comment by slush0** [comment]
Imo one thing is to fix the wording (seller/buyer depending on the tab) whicu is rather trivial to fix.

Anothe thingy is the whole discussion how to improve UX and make it easier to understand and we need to discuss it here.

**Comment by leomira** [comment]
let's fix the functionality first, then we can discuss it again.
