### ISSUE TITLE
Make 2nd degrees offer default

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#33]
Currently created offers are set to be 1st degrees only. Default should be 2nd degree.

**Comment by leomira** [comment]
@mpocuch pls acknowledge that we are currently considering this issue to be deferred. 

we will proceed with this once we optimize the offer encryption algorithm.

**Comment by slush0** [comment]
This is needed again :).

**Comment by leomira** [comment]
seems to be working on Android already

**Comment by leomira** [comment]
@prusnak can you try this on iOS please?

**Comment by leomira** [comment]
works 🎉
