### ISSUE TITLE
Use currency codes consistently

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#335]
Please make the use of currency shortcuts consistent across the app.

Currently, there is "Czech crown" in the menu, "CZK" in create offer and then suddenly "Kč" appears in the marketplace.

I don't have *strong* preference if we should use currency codes "CZK / EUR / USD" or symbols "Kč / $ / €", but it should be at least consistent in the settings menu, create offer form and marketplace.

**Comment by slush0** [comment]
Relevant to #234 and #320.

**Comment by prusnak** [comment]
Fix in https://github.com/vexl-it/vexl/pull/336
