### ISSUE TITLE
Social network updates & Explanation

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#341]
As discussed at #291  I would like to continue a discussion regarding the updated approach towards "direct friend" situation in the social network. 

Below I propose a quick fix solution (before we rewrite the contact microservice) with a UX suggestion. 

We have the information popup already designed (attached here), I would reuse it in the request dialogue.

I suggest this wording:
"What does this mean?" + button "Check it out" or "Learn more"

On the popup that follows we should communicate:

situation no1 - you are a direct friend with 0 common friends
headline: Offer from a direct friend
You see this offer because the counterparty has your phone number saved in their contact list. Be cautious, we cannot verify if you really know each other in the real life.

situation no2 - you are a direct friend with XY common friends
headline: Offer from a direct friend
You see this offer because the counterparty has your phone number saved in their contact list. Don't forget to verify their identity with a common contact.

situation no3 - you are a 2nd degree friend with XY common friends
This is a contact with whom you have no direct connection. Don't forget to verify their identity with a common contact.

I think it would be best to always show the popup according to the state of the request rather than show one long dialogue explaining all three.

<img width="315" alt="Snímka obrazovky 2023-06-21 o 11 17 15" src="https://github.com/vexl-it/vexl/assets/25779015/531bdd4c-c473-4acf-b429-82c9edfc3645">

**Comment by kaladivo** [comment]
Please continue working on this in: #340
