### ISSUE TITLE
Counterparty deleted account - Chat inconsistency

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#342]
I am describing a situation when users already connected via chat, but then one of the users deleted the account. 
Currently it is inconsistent how the chat behaves when the users revealed their identity vs. when they didn't. 

Without the identity revealed, we have a communication pattern, which is imho correct:
1. we inform user, that the offer was deleted
2. then we inform, that the user left the chat
3. we prompt to leave the chat too.
![signal-2023-06-21-124431_002](https://github.com/vexl-it/vexl/assets/25779015/a78443d9-e417-44ed-b560-dad7104ae689)

With the identity revealed, the chat informs the user that the counterparty deleted the offer and prompts him to leave the chat. 
This is not correct, this user deleted their account and it is not possible to get in touch with them again. The pattern should look the same, just with deanonymized name: 
1. inform, that offer was deleted
2. inform, that counterparty left the chat
3. prompt to leave the chat too.
![Image from iOS (1)](https://github.com/vexl-it/vexl/assets/25779015/9033f892-05a9-4fa9-9c09-aef02ab5b8c1)

Note: I updated the copy so it is more explanatory (i.e. change the word "inbox" to "chat".)

**Comment by kaladivo** [comment]
Moving to blocked. This behaviour might be changed by #263. Let's implement this after we merge that one.

**Comment by leomira** [comment]
this is fixed with the recent updates of #263

**Comment by leomira** [comment]
Sorry for closing, my bad. So no, the problem still persists. @kaladivo moving to todo

**Comment by leomira** [comment]
This is not fixed, the behaviour remained the same. Moving to todo.
