### ISSUE TITLE
Layout broken due to flag button on chat detail

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#371]
![Snímek obrazovky 2023-07-04 v 15 33 36](https://github.com/vexl-it/vexl/assets/11568934/4eaeeb14-e783-40aa-959f-ae786e48a904)

Possible solutions: 
1. ~~Move flag button to ChatInfoModal~~ it's already there, so maybe we could just remove this button from the chat header

**Comment by SamTremko** [comment]
@kaladivo if you mean the text in header going too many lines down, I did this on purpose to fit the button to header. I suppose there is no better solution for this one. The button was added there as @leomira wanted it to be there. So maybe we let @leomira decide?

**Comment by leomira** [comment]
I would just move the element to the left, so it has the same layout as it had before, but keeping the flag button. @kaladivo @SamTremko 

If it is a problem with i.e. different resolutions and so on, we can eventually remove the flag button.

**Comment by kaladivo** [comment]
Yes, this will definitely overflow on smaller screens. My suggestion is to remove it completely and leave it in chat modal that opens after header is clicked. 

Another option would be to make the text or profile picture smaller.

**Comment by leomira** [comment]
alright, it makes sense to remove the button then, let's not break the font size.
