### ISSUE TITLE
Empty marketplace: Bug in the countdown

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#374]
I don't know what this number is, but certainly it is not correct 😅 

![Screenshot_20230711-140044 (1)](https://github.com/vexl-it/vexl/assets/25779015/60a2a252-ab2e-4cde-a079-675d2b867307)

**Comment by SamTremko** [comment]
@leomira I think this bug happened when user had reach number more than 30 Vexlers (this is our threshold) and there was still no offer in the marketplace. So I suggest that either we keep the message like: Offers are loading and should be ready for you in 1 minutes after the countdown hit 1 and there is still no offer. Also we keep refreshing offers state each minute to check if there is any new offer for the user.
The other solution can be, that we display some fallback message like add more contacts and after user ads more the countdown resets to 60 minutes again.

**Comment by leomira** [comment]
@SamTremko I think this is unlikely, it was my phone.

**Comment by leomira** [comment]
Alright, let's go with the first option.
