### ISSUE TITLE
Offer with empty location

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#377]
![Screenshot_20230712_215834_Vexl 20](https://github.com/vexl-it/vexl/assets/11568934/c1377ed8-52d5-45f5-b552-94d913d3f36e)

**Comment by leomira** [comment]
@SamTremko moving this back to todo, the problem still occurs (v 1.1.5 (50))
))
![signal-2023-07-31-141442_002](https://github.com/vexl-it/vexl/assets/25779015/1c50d860-65e5-45ec-a6a4-9f9e15dcc1d1)

**Comment by SamTremko** [comment]
@leomira are we sure this is not the old app?

**Comment by leomira** [comment]
No, not at all. I will try to reach out to the owner of the offer and ask.

**Comment by leomira** [comment]
@SamTremko So this occured after the owner used just "Ustecky kraj" without specified city.

App version 1.1.2

might be connected to #271

**Comment by SamTremko** [comment]
Ah ok that will help, let me check

**Comment by SamTremko** [comment]
@leomira from version 1.1.3 and above there should be no such thing as empty location for offer. I implemented the condition there to filter results that do not contain 'city' in location suggestions. For already created offers with empty location we cannot do anything, as they contain in the location data only latitude, longitute and city as empty string. So we do not have any substitude in offer data to display.

**Comment by leomira** [comment]
alright, thanks for clarification!
