### ISSUE TITLE
Warn in onboarding when registering an existing number

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#382]
If an user registers with the same older as they registered previously on another device, the older device will be "deactivated".

Warn an user on new device this is going to happen before they continue.

**Comment by leomira** [comment]
note: must happen after receiving the verification code in order to prevent doxxing that a number was already verified

**Comment by kaladivo** [comment]
The flow: 
1. user loggs in on user service (up to, including `verifyChallenge` endpoint)
2. Before continuing in the flow and saving user to local state, client calls contacts service endpoint [`checkUserExists`](https://github.com/vexl-it/vexl/pull/724/files#diff-3548719efcc6e89385de2b0c1e17ad108648ecfe33c03db519f5b91a12dd3981R56)
3. If user exists askAreYouSureAtom modal is presented with options to: 
  a. Cancel login - which will delete previous user -  call delete user on user userService [deleteUser](https://github.com/vexl-it/vexl/blob/7e9c55d323e4ea1680976ca5746a925dafa39007/packages/rest-api/src/services/user/index.ts#L171-L172) and start the login flow again
  c. Continue into the app - force login - it will just resume the flow as before
4. If user does not exist it continues as previously

**Comment by leomira** [comment]
this works fine! just one thing, @SamTremko please correct how we redirect a user after they cancel the new phone number registration: 
currently: 
1. press cancel button
2. onboarding screen

should be: 
1. press cancel button
2. back to phone number input

also, can we show some warning message in the device which is being deregistered? (dont have to do it asap, I would open a separate issue, just curious)

**Comment by kaladivo** [comment]
> also, can we show some warning message in the device which is being deregistered? (dont have to do it asap, I would open a separate issue, just curious)

We can, it's actually pretty good idea!

see #784

**Comment by kaladivo** [comment]
Should work now. Needed to enable it on BE.
