### ISSUE TITLE
Rename Import contacts to Manage contacts in Profile menu

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#40]
In Profile menu, rename Import contacts to Manage contacts. Currently it is unclear that you can also un-import/manage existing contacts in the app.

**Comment by leomira** [comment]
Done, it will show when the next build is pushed to appstores and reviewed.

**Comment by prusnak** [comment]
> Done, it will show when the next build is pushed to appstores and reviewed.

Where is it done? I don't see it changed in `Vexl Localizations` spreadsheet?

**Comment by leomira** [comment]
@prusnak line 125
