### ISSUE TITLE
Schedule event once both sides agree on trade date/time

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#408]
We can schedule notification or show button to add a slot to the calendar

**Comment by kaladivo** [comment]
Blocked by #283

**Comment by leomira** [comment]
How can I test this @SamTremko ?

**Comment by SamTremko** [comment]
Sry @leomira the title is outdated a little, as all settled events in trade checklist schedule notification, the main goal of this task was, after the date and time is settled, user can add the event to the calendar. Also when location is settled it can be also added to the event in calendar

**Comment by SamTremko** [comment]
@leomira and its only merged in main, this one is not on staging yet

**Comment by leomira** [comment]
@SamTremko ah sorry for this (and the other comment),  Dejv told me to test everything from code review on

**Comment by leomira** [comment]
pure beauty, works without a single problem

**Comment by leomira** [comment]
ok couple of teeny-tiny issues @SamTremko 

1. when we agree upon date/time
without identities revealed
and add event to calendar
and then we reveal identities
and I add the event to the calendar again 
-> it does not update according to the revealed identity
(this is a total edge case and no need to pay to it too much attention)

2. when we agree upon date/time
and then I change the location
and update the calendar link
the comment from the previously agreed location remains in the description of the event.
(another edge case, just might be unpleasant for someone )

3. after successfully adding event to a calendar
and then agreeing on location
I get a message "Event successfully added", Event was added to your calendar for the settled date and time.
I should get:"Meeting location successfully updated" Event was updated for the preferred date and time. 

4. I would like to add some validation to the buttons after the adding to calendar was successful. Just change of the copy of the buttons would be sufficient:
- Add event to calendar -> Event added to calendar
- Update calendar event with location-> Meeting location was updated

copy update: 
if we change the details of the deai
and then I update calendar event 
I am getting a copy saying the event was added.
it should say it was successfully updated.

**Comment by SamTremko** [comment]
@leomira regarding the point 4., I tried some approaches and I would say, let's leave it as it is and see what users will say about that, or what comes out from app audit. As it seems just like small change, just change the copy on the buttons, it requires som more complex logic in app and I am afraid we can come to some inconsistencies as:

1. user can create event and update location, than delete event in calendar manually and return to app, or delete just location from the event and return to the app (we would need to check on each chat open if the chat has some event connected to trade checklist in calendar and what are the props of the event)
2. then there can be some value stored in app regarding the event details which can be not synced to the event in calendar and then we would display misleading information on buttons copy

For now the copy on the buttons will not be changed, just after user presses the button to add event once more, he will get message, that the event was UPDATED and not CREATED as it was before. It will not create extra event on each press, just update the one already created again and again. The same with the location. Let me know, what you think.

Topics from point 1.-3. should be fixed, thx for reporting them.

**Comment by leomira** [comment]
@SamTremko 
regarding 4 - no problem 🤝 

will check the rest!
