### ISSUE TITLE
Fix 1st degree / 2nd degree graphics

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#44]
Figma:

<img width="399" alt="Screenshot 2022-09-19 at 11 33 48" src="https://user-images.githubusercontent.com/42201/190989793-d769953b-a4f3-4d33-8efc-afde8e8a0c3e.png">

Real device (iOS):

![IMG_1325](https://user-images.githubusercontent.com/42201/190990020-9e16d972-6f3b-48d4-a0a6-abfb873303ad.jpg)

Also, why there is an old guy in the photo? Let's replace with user's avatar.

**Comment by leomira** [comment]
This is a bug on iOS. This is correct on Android.

**Comment by prusnak** [comment]
> This is correct on Android.

Is there a user's avatar on Android?

**Comment by slush0** [comment]
On Android, yes.
