### ISSUE TITLE
Images disappearing after updating app 

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#440]
After updating the app to newest version profile photos are disappearing. It also frequently happens after deleting a chat. On staging and production  iOS 1.1.8 (56) and 1.2.0 (59)

![IMG_6066](https://github.com/vexl-it/vexl/assets/143531040/45b3e210-4db2-4eb2-b5b0-8b61e1b7f011)

**Comment by prusnak** [comment]
Can confirm on 1.1.9 on iOS 16.6, but this had happened on 1.1.7 too.

**Comment by kaladivo** [comment]
Ios changes document directory as it sees fit. https://developer.apple.com/forums/thread/92693 

One way to replicate this reliably without reinstalling the app is to change the phone's language.

Should be fixed here: #443
