### ISSUE TITLE
Creating offer for buying but defaults to sell 

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#444]
UX issue. 

![IMG_6084](https://github.com/vexl-it/vexl/assets/143531040/cc6c4d9c-b18f-4cb2-85c3-d0813cf2b7fe)

Many offers to buy are ending up in the selling marketplace because when creating an offer to buy the first option defaults to sell. Maybe it's possible to have it default to the market where the + was tapped? 

So:

if I am on sell market tapping the + will create sell offer. 

If I am in the buy market tapping the + will default to buy. 

https://github.com/vexl-it/vexl/assets/143531040/31c69ddf-f4b4-407f-934a-bcb3a642d06d

**Comment by prusnak** [comment]
The solution is not to preselect any direction and force user to select in the offer creation form. 

We also talked that we should hide all other parts of the create offer form until this is set. Then unfold all of other settings, not one by one.

**Comment by leomira** [comment]
solved with #451
