### ISSUE TITLE
Make clear who is offer maker/offer taker

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#448]
Currently, it is not possible to distinguish if you're in the chat regarding your offer or an offer of someone else. 

Let's implement a sticky bar as it was originally designed that would communicate the details of the offer we are talking about.

Also it should name its author -> either me or a counterparty. 
That means either randomized name or the user name (if there was a successful identity reveal.)

[Design](https://www.figma.com/file/wyegUA8byXpHymF5lXxnkq/Vexl-App-V2.0-UI?type=design&node-id=0-1&mode=design&t=yT9XhVQ2IPwIBeKm-0)

**Comment by leomira** [comment]
I propose few small adjustments:
1. let's add option to close the sticky bar (with X)
2. let's indicate with color "me" or "counterparty"
and
as it is confusing to see the original request in the detail of the offer, in the situation where the counterparties are already connected via chat, let's update how the offer/request detail looks like redesign the card of the offer detail as it follows: 
1. Their offer/Your offer
2. common friends
3. let's not show the text of the request


![Image](https://github.com/vexl-it/vexl/assets/25779015/413a878c-7333-4382-85b6-3ae13368a0eb)

**Comment by kaladivo** [comment]
@leomira Where should the me/counterparty indication be? On the sticky bar?

**Comment by leomira** [comment]
@kaladivo yes, AFAIK it is already implemented, i would just like to add the option to close the sticky bar. 
it is here where I suggest that me/counterparty text could be colored

**Comment by leomira** [comment]
works perfectly
