### ISSUE TITLE
Improve visual separation of the offers

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#45]
It is unclear which user belongs to a particular offer. 
We need better visual separation of the offers on the marketplace. 
![IMG_7386](https://user-images.githubusercontent.com/25779015/191006565-e58390e0-3484-4809-8408-8eac638c4280.png)

**Comment by leomira** [comment]
It is much clearer on Android, where the card shows in a form of a comix bubble. 

![Screenshot_20220919-164959](https://user-images.githubusercontent.com/25779015/191021362-1588817d-0b2d-471b-a9e1-827163e7cf3c.png)

**Comment by leomira** [comment]
@prusnak we were trying this, but it was an informational mess. Too many things being shown on the card, it did not work at all. I would go for updating iOS according to Android and making the whole card clicklable.

**Comment by prusnak** [comment]
> we were trying this, but it was an informational mess.

OK. The bubble is nice!

**Comment by slush0** [comment]
Comic bubble it is  then!

**Comment by mpocuch** [comment]
ETA 27.9.

**Comment by leomira** [comment]
Why is the ETA 27.9. if it is literally just little update - turning the
white card into comix bubble, as we already have on Android?

**Comment by mpocuch** [comment]
@leomira because it doesn't make sense to make build with every little fix separately - it is huge overhead just for the preparation of the build and it is not effective. therefore we aim to deliver it together with other stuff in a "package". if you need this to be fixed with highest PRIO and in separate build, pls let us know, we can do that - but as I said it is not effective

**Comment by leomira** [comment]
As we spoke and agreed earlier with @tomstibor, for the issues that are
done just waiting to be deployed please use appropriate column in the GH
project.

We can also add new column, like done/waiting for build or smt like that,
if it helps.

The goal is to know that bugs (and which bugs in particular) are taken care
of and to see what stage they are in.

**Comment by mpocuch** [comment]
"waiting for deployment" or "waiting for build" would probably make sense if we agree that we will not need to prepare DEV builds after each fix / task

**Comment by leomira** [comment]
So my point is: no need to prepare a separate build for every single minor
bug at all.

BUT

1. high prio issues must be shipped without delay
2. we need to be able to see progress on the other issues that you are
working on. if the GH projects kanban does not work for you, give us an
alternative please.

**Comment by mpocuch** [comment]
the GH kanban is fine.. if we can introduce that one column extra, would be ideal.. P1 issues will be shipped without delay - clear. unfortunately all issues in P1 are not as easy-fixes as this one (which is labeled as P2).. so the P1 issues are also driving the ETA of P2 issues (such as this one).

**Comment by leomira** [comment]
Gotcha, glad that we made it clear 🤝

Will create the column ASAP.

**Comment by leomira** [comment]
@mpocuch column in place, dont hesitate to use it 🥇
