### ISSUE TITLE
Re-encryption of offers for newcomers doesn't work as expected

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#46]
Currently, when new user joins, the backend sends silent notification to the App of his contacts, and when the App is started, it should re-encrypt the offer and publish to the backend. Then the newcomer will see the offer.

There's a improvement proposal in #22, but it assumes that mechanism described above works as expected.

In last two days, I twice hit a issue where the mechanism described above didn't work and the offer was not re-encrypted for newcomer:

Situation 1:
1. Let's have existing User A (Android) and user B (iPhone), and new installation and registration for user C (Android)
2. Everybody has each other in contact list and imported to Vexl.
3. Everybody has working notifications.
4. Both A and B have existing offers.
5. After installation, user C does not see any offer (expected).
6. User A closed and opened the app, and offer for user C appeared (expected).
7. User B closed and opened the app, and offer for user C does not appeared (not expected).

I tried several things, we waited for about a hour, and the offer from user B simply didn't appeared. What however I forgot to try was to Edit and Update the offer on the user B phone, because:

Situation 2:
1. Let's have the same existing User A (Android) as in situation above and new installation and registration for user D (Android)
2. Both has each other in contact list and imported to Vexl.
3. Both has working notifications.
4. User A has existing offers.
5. After installation, user D does not see any offer (expected).
6. User A closed and opened the app, and offer for user D does not appeared (not expected).

I tried to restart both applications several times, wait for some time and nothing helped. Then I had an idea an edited and updated the offer of user A. After the process finished, the offer instantly appeared on phone D. I successfully performed this twice as user A had two active offers.

Conclusiton is that the process of re-encryption as it is now is not robust enough and does not work as expected. From two situations described above is clear that it is not something specific for one particular installation, device or operating system. For example, in situation 1., everything worked as expected for user A, but didn't work at all in situation 2. Also on receiving side, it was both iPhone and Android, so it is not platform specific.

My guess is that similar bug could be caused by notifications somehow getting lost in the system after registration of new device, so some peers does not learn there's new public key to encrypt to.

**Comment by leomira** [comment]
@tomstibor what's the ETA for this issue?

**Comment by slush0** [comment]
Situation 1 has been very likely caused by #55. I *know* that user B (iPhone) declined the notifications in onboarding, and enabled them later in phone settings.

**Comment by mpocuch** [comment]
ETA 27.9.
