### ISSUE TITLE
UX optimization of Profile screen - Reach

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#465]
Currently when you install the app it takes some time before the marketplaces and social reach fully loads.

I propose that right after the onboarding, we should indicate in the profile screen that "your reach" is counting, preferably with a copy "Counting..." and the three dots animated.

**Comment by kaladivo** [comment]
@leomira 
Social reach is calculated right away after submitting contacts. There was a delay in previous versions but there is no delay anymore. Can you please clarify when exactly is the number not updated / if this is still a problem? 



https://github.com/vexl-it/vexl/assets/11568934/fbb387a6-4442-4727-bc62-bd34c38b583f

**Comment by leomira** [comment]
Ok, closing the issue, the count was loaded almost immediately.
