### ISSUE TITLE
Make whole offer card clickable, not just the request button

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#47]
Having the ability to request an offer directly by clicking on it is much more intuitive.

**Comment by prusnak** [comment]
Related to https://github.com/vexl-it/vexl/issues/45

Maybe we can move `XXX is buying/selling` + the `Request` button inside of the white offer bubble?

**Comment by prusnak** [comment]
My suggestion is to:
* make the green regions clickable (not only offer card, but also the person card)
* remove the "Request" button (marked with red) - it's really redundant and kind of confusing after we make the whole card clickable 

![IMG_F8FF5995B5D7-1](https://user-images.githubusercontent.com/42201/192813939-804f957c-043d-40ff-959d-092de0b6eebc.jpeg)

**Comment by leomira** [comment]
works fine on Android
@prusnak please note that after discussions with designer, we decided to keep the request button, as it is needed for additional management of requested offers and so on (like #75  or #88 )

**Comment by leomira** [comment]
works 🎉
