### ISSUE TITLE
Initial message (request) not displayed in the chat.

### ISSUE THREAD

**Issue by zaplmi** [vexl-it/vexl#48]
After sending (and accepting) the request to the offer, the initial message (from the requester) is not displayed in the chat.
Which is not ideal because it might contain important info.

![image](https://user-images.githubusercontent.com/91535734/191027913-1197dd80-e9c4-4129-9382-66b8a73e0c4d.png)

![image](https://user-images.githubusercontent.com/91535734/191028067-8da62e61-117e-4b0c-b4e8-d1f3ace3128a.png)

**Comment by prusnak** [comment]
Good idea! Be careful, for one user in the conversation info needs to appear on the left side of the chat, for other user it needs to appear on the right side of the chat.

**Comment by leomira** [comment]
shipped in 1.0.10
