### ISSUE TITLE
QR Code Scanner for convenient contact sharing 

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#483]
Currently it is not possible to scan a counterparty's QR code directly in the app. 

The current flow requires the use of a third party QR code reader or the camera app. 

It would be much easier for people to share contacts if the Vexl app had a QR code reader that could read and import a contact directly in the app.

**Comment by leomira** [comment]
few issues: 
1. please, let's round the corners of the camera, as we have it everywhere in the app 🙏 the plain square hurts my eyes
2. if I have the contact already saved, it works fine
3. if I don't have the contact saved, there is a bug, see the pic: 


![Image](https://github.com/vexl-it/vexl/assets/25779015/18688086-dec5-40ab-818d-0c8ee32335ec)

**Comment by kaladivo** [comment]
That is Czech translation being bad. Does it work with english language?
