### ISSUE TITLE
Banner with link to a new app

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#486]
Let's put a banner linking to the new app to Vexl 1.

**Comment by kaladivo** [comment]
Sadly, we are not able to update the app after we have removed it from the app store. See: 

https://support.google.com/googleplay/answer/12246761?hl=en#:~:text=What%20happens%20if%20an%20app,able%20to%20update%20your%20app.

https://stackoverflow.com/questions/42866187/removing-an-ios-app-from-sale-while-still-providing-updates-and-support#:~:text=1%20Answer&text=Highlights%3A,you%20have%20an%20active%20contract.
