### ISSUE TITLE
Closable banner with "friend" explanation on Request screen

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#487]
Let's not show this banner once a user closes it.

![signal-2023-09-10-023437_002](https://github.com/vexl-it/vexl/assets/25779015/fe1ff474-51f3-4d94-b230-47f566ae922e)

**Comment by kaladivo** [comment]
@leomira Should we do the same with online location banner?  

![Image](https://github.com/vexl-it/vexl/assets/11568934/e4329922-1593-4f70-85e9-a738ca3a30ea)

**Comment by leomira** [comment]
@kaladivo in this scenario I would keep it there.

**Comment by leomira** [comment]
@kaladivo once an explanation is closed it should not appear again (i.e with other request). can you check it out? 

watch out we have 2 types of these: friend and friend of friend

**Comment by kaladivo** [comment]
I have tried this and it works for me. Can you confirm that this does not work for you?
