### ISSUE TITLE
A list of active offers is hidden under the "Create new offer" button

### ISSUE THREAD

**Issue by vbspam** [vexl-it/vexl#5]
A list of active offers is hidden under the "Create new offer" button.

**How to reproduce**
1. Create an offer ABC.
2. Try to access the offer ABC.
3. Open the offer list through "Create new offer".

**What happens**
The list of active offers is hidden under the "Create new offer" button.

**Expected behavior**
The list of active offers shall be accessed under a meaningful name or icon.

**Comment by slush0** [comment]
Agree, and I propose to leave "Create new offer" in Buy/Sell tabs, but allow displaying my offers in Profile section ("My offers").

**Comment by leomira** [comment]
already working on this, this is a duplicate of an issue https://github.com/vexl-it/vexl/issues/35 so I am closing this.
