### ISSUE TITLE
Btc -> honey

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#509]
Simple function to run agains every translation object will work: 

```typescript
export default function replaceBitcoinWithHoney(obj: AnyObject): AnyObject {
  if (obj === null || typeof obj !== 'object') return obj

  for (const key of Object.keys(obj)) {
    if (typeof obj[key] === 'string') {
      obj[key] = obj[key].replace(/bitcoin/g, 'honey')
      obj[key] = obj[key].replace(/Bitcoin/g, 'Honey')
      obj[key] = obj[key].replace(/Bitcoins/g, 'Honey')
      obj[key] = obj[key].replace(/bitcoins/g, 'honey')
      obj[key] = obj[key].replace(/BTC/g, 'HON')
      obj[key] = obj[key].replace(/btc/g, 'hon')
    } else if (typeof obj[key] === 'object') {
      replaceBitcoinWithHoney(obj[key])
    }
  }

  return obj
}
```

There are also elements that imply bitcoin but can not be translated so easily.

## BTC price
Btc price is also referenced at new offer form
![Snímek
obrazovky 2023-10-02 v 9 47 32](https://github.com/vexl-it/vexl/assets/11568934/c1fa5c6d-2f1f-4d27-920b-675667a08f5f)

## Lightning or onchain
![Snímek
obrazovky 2023-10-02 v 9 49 24](https://github.com/vexl-it/vexl/assets/11568934/900b453c-547b-4900-bbbf-0be0aae404fa)

##  Payment method
![Snímek
obrazovky 2023-10-02 v 9 50 02](https://github.com/vexl-it/vexl/assets/11568934/e63a994c-afd5-40c1-9c6f-157708ca3a88)

**Comment by prusnak** [comment]
Let's close this for now.
