### ISSUE TITLE
Onboarding - UX Simplification of Contacts Management

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#511]
In the interest of network scaling and a smoother and faster onboarding process, I propose a simplification of the onboarding, to be precise, in the part of contacts management:

Currently, during the onboarding, the contacts import has two steps:
1. intro & explanation 
2. contacts picker

I propose to remove the contact picker part and import *all* contacts by default directly on this screen - so after pressing "import contacts" button, we move in onboarding on to enabling notifications. 
We should slightly change the wording here too - what about:
*Vexl connects you with your friends and friends of their friends. Later you can manage which contacts you want to include in your social reach.*

- watch out, current implementation does not select any contacts -> all contacts must be "checked" before import, so we don't import an empty one

**Comment by satsdisco** [comment]
I like this copy:

_Vexl connects you anonymously with your friends and friends of friends. You can later manage your contacts and choose which ones you want to include in your social reach._
