### ISSUE TITLE
Notifications - UX improvement

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#52]
Notifications about incoming requests need a bit love. 

For now it is a low prio, but we should definitely pay an attention to it after we update the offer creation and onboarding process.

**Comment by leomira** [comment]
![signal-2022-09-20-122533](https://user-images.githubusercontent.com/25779015/191207372-9121f5bb-33e4-415f-bd31-d1c1fa4b4365.png)

**Comment by slush0** [comment]
IMO duplicate of #28. Please add it as a subtask there.

**Comment by leomira** [comment]
Moving this to #28
