### ISSUE TITLE
Chat notifications grouping

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#534]
This is just Android feature. On iOS we need to use [categories](https://notifee.app/react-native/docs/ios/categories) .

AC: 
- All notifications regarding chat should be grouped [see example here](https://notifee.app/react-native/docs/android/foreground-service)
- Use use notifee groupId property to group them - as the key should be used ```sha256(
      `${notificationData.data.inbox}${notificationData.data.sender}`
    )``` if for whatever reason the hash outputs too long value use some shorter hashing function (or trim the result but carefully to prevent generating the same output for different inputs)

How to test (android only): 
- Open chat between A and B
- A closes the app
- B sends 2 chat messages and request for anonymization
- A should see 3 notifications pop up but grouped

**Comment by kaladivo** [comment]
wip in `feat/group-notification`

**Comment by leomira** [comment]
wasn't this released already?
