### ISSUE TITLE
Are you considering a web version (PWA) of Vexl?

### ISSUE THREAD

**Issue by sirluky** [vexl-it/vexl#535]
Hello,

given the challenges faced with the iOS version of Vexl, have you considered the possibility to create a web version?
I have quickly looked up the dependencies and features you use and most of it should be no problem to implement as PWA.

**Comment by kaladivo** [comment]
Hi, currently due to technical limitations we don't plan to do web version of Vexl. The problem is that Vexl relies on background tasks that can not be reliably implemented in PWAs as of yet.
