### ISSUE TITLE
Messages disapear in chat

### ISSUE THREAD

**Issue by SamTremko** [vexl-it/vexl#536]
Lets have this scenario. I have both apps opened in simulators.

1. I send message: Msg1 from Android device to iOS device.
2. Then send message: Msg2 from iOS device to Android device.
3. Android device receives Msg2
4. As on iOS simulator are real time notifications not supported, iOS device did not receive Msg1 from Android, but sees Msg2 that he sent to Android in message history
5. After putting app on background and then back, iOS device received Msg1 from Android, but it replaced Msg2 in message history, that was previously sent to Android device from iOS device

This is maybe just case of simulators, but i real scenario when either of devices does not receive notification correctly, it can cause messages in chat to disapear. It is worth to check and rather fix this issue.

**Comment by kaladivo** [comment]
Should be fixed by fixing add to sorted array function
