### ISSUE TITLE
Check qr code scanner and exchange of contacts

### ISSUE THREAD

**Issue by SamTremko** [vexl-it/vexl#545]

**Comment by leomira** [comment]
@SamTremko is this still relevant?

**Comment by SamTremko** [comment]
@leomira don't know, I think this was reported by @slush0 after Kolin meetup, that the scanner does not work OK, did not have time to check it since then

**Comment by SamTremko** [comment]
@leomira tested, seems to be working, contact is added to Vexl contacts, closing
