### ISSUE TITLE
Import contacts optimization (Long load times)

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#547]
If a user has an extensive list of contacts (over 1000), the app may take a significant amount of time to populate the "Import Contacts" section. 

This delay often leads users to bypass the contact importation step, which is crucial for building their Web of Trust (WOT).

To mitigate this issue, we could display a message that says, "If you have a large number of contacts, please be patient while they load into the Vexl app before moving on to the next step." 

Users have reported that the app appears unresponsive during this time due to the high volume of contacts in their address books.

"App is slow, but only while importing contacts."

**Comment by kaladivo** [comment]
There is already a loading indicator on contact list. 

Let's try to simulate this in emulator with 1 000 dummy contacts or so and if it is still slow, find a way how to properly communicate loading state to the use.

**Comment by satsdisco** [comment]
This is still an issue. seen first hands phones overheating and becoming unusable when there is a high number of contacts.

**Comment by satsdisco** [comment]
![CleanShot 2023-12-07 at 13 04 03@2x](https://github.com/vexl-it/vexl/assets/143531040/ef4283f5-5b15-4499-8bb4-7c5bf50103c9)

User with Pixel 6 cannot get past the import contacts screen. It continues to load for over 2 days.
