### ISSUE TITLE
Actively check if notifications are enabled and working on startup

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#56]
As notifications are essential for application to work, the app should check if notifications are enabled and properly configured (see bug #55) on the application startup. If they're not enabled, dialog explaining the importance of notifications should appear, with CTA for enabling them (see #26).

**Comment by mpocuch** [comment]
+ do not allow user to enter the app if notifications are disabled -> new screen to navigate user to settings to enable them

**Comment by leomira** [comment]
works 🎉
