### ISSUE TITLE
Postpone photo upload and nick edit until the first reveal identity

### ISSUE THREAD

**Issue by prusnak** [vexl-it/vexl#575]
to make onboarding easier

To be discussed...

**Comment by leomira** [comment]
I was just about to open this issue, had the same idea. 

My reasoning: 
1. users skip it either way
2. it feels like KYC to paranoia maxis
3. onboarding is too long, users get confused about "identities"
4. it is not used or necessary in the app's workflow anywhere except the identity reveal (other thing would be if we implemented #281 )

**Comment by kaladivo** [comment]
Ash was also talking about this. I like the idea of requesting user photo (and even the name) right before identity reveal. The one important thing we need to be avare of is, that we need to communicate that user sharing his/her info wont reveal it to everyone but only the users that are approved...

**Comment by kaladivo** [comment]
Allow user to save image / name for other chats there should be checkbox for `save for later reveals` if not checked identity is not saved globally (only sent to other side).
