### ISSUE TITLE
Links missing from FAQs?

### ISSUE THREAD

**Issue by BTCparadigm** [vexl-it/vexl#589]
I was reading through the FAQs in the app and I noticed two slightly confusing sections:
<br>

1. Where is "here"? Should there be a link somewhere?
![image](https://github.com/vexl-it/vexl/assets/51679301/22895d1f-b576-4902-93e3-b0567f56b4ca)
<br>

2. There is no ToS or Privacy policy below. Is it missing a link or have those sections moved their place in the app, because now they are above FAQs?
![image](https://github.com/vexl-it/vexl/assets/51679301/829d999e-f306-4645-a861-82753cb462a5)
![image](https://github.com/vexl-it/vexl/assets/51679301/f4a30f04-80dd-4874-9f08-05a54d694655)

**Comment by kaladivo** [comment]
Hello, thanks bringing this up. We will look into it.
