### ISSUE TITLE
Add timeout or wait for response on identity reveal request

### ISSUE THREAD

**Issue by danmyway** [vexl-it/vexl#59]
Issue:
When requesting the identity reveal it is now possible to spam the request button.

Possible solution:
Add a timeout to the request button.

Reproducible on Android, not reproducible on iOS
CC: @seberm

https://user-images.githubusercontent.com/8378124/191283710-0b67dbb1-5191-446d-9d2b-bd5d7b2c1395.mp4

**Comment by slush0** [comment]
When the other side is an idiot, Delete chat or Block contact is here FTW :-).

On serious note, thanks for report!

**Comment by leomira** [comment]
works now!
