### ISSUE TITLE
Word is divided between two lines

### ISSUE THREAD

**Issue by BTCparadigm** [vexl-it/vexl#590]
### Description
The word "contacts" get broken down in bad way from readability and aesthetics point of view
![image](https://github.com/vexl-it/vexl/assets/51679301/e13a03e5-9fcd-42be-882a-900cc8120295)

### Version
1.7.4 (89)

**Comment by kaladivo** [comment]
Hello, 
thank you for the bug report. 

Can I ask what is your screen resolution? Do you use Android UI zoom feature?

**Comment by BTCparadigm** [comment]
Glad to help.
My screen resolution is 1080 x 2400, and no, I don't use the zoom feature.
