### ISSUE TITLE
Impossible to enter Czech diacritical marks on iPhone

### ISSUE THREAD

**Issue by vbspam** [vexl-it/vexl#6]
There is impossible to enter Czech diacritical marks on iPhone.

**How to reproduce**
1. Create an offer.
2. Enter the offer description in Czech language by using Czech diacritical marks e.g. "Čau lidi a motýle"

**What happens**
The Czech language diacritical marks can not be entered properly. The text appears as follows "Cˇau lidi a moty'le"

**Expected behavior**
The Czech language diacritical marks shall be possible to enter properly. The text from example shall be "Čau lidi a motýle"

**Platform**
iPhone 13 mini 15.6.1

**Comment by Hannsek** [comment]
The diacritical marks actually can be entered properly by long pressing one letter and then choose from the tab above the letter.

**Comment by adamusel** [comment]
Retested on the lastest build of app and everything works well.

**Comment by leomira** [comment]
which build was it please? is it in review already? if yes, then please
move the card to the appropriate column

**Comment by jkuchar** [comment]
This is fixed.

**Comment by prusnak** [comment]
Confirmed
