### ISSUE TITLE
Add Albanian LEK currency

### ISSUE THREAD

**Issue by HostFat** [vexl-it/vexl#610]
Can you add the support for listing LEK (Albania currency) offers?

https://en.wikipedia.org/wiki/Albanian_lek

**Comment by leomira** [comment]
add Bulgarian & Romanian shitcoin too please

**Comment by leomira** [comment]
(tbd: coingecko implementation)

**Comment by HostFat** [comment]
Not sure if useful, but now ALL (Albania currency) is available here
https://api.yadio.io/exrates/BTC

**Comment by SamTremko** [comment]
Moving to blocked, as CoinGecko does not support LEK, LEI or LEV for now. I can contact them about their plans regarding those.

**Comment by HostFat** [comment]
@SamTremko can you use https://api.yadio.io/exrates/BTC instead of Coingecko for ALL?

**Comment by leomira** [comment]
connected to #980

**Comment by leomira** [comment]
@SamTremko I am moving this issue back to To do, I don't see ALL in the app. 

It is a low priority for now, no need to fix it asap.

**Comment by HostFat** [comment]
LEK is "ALL" value here:
https://api.yadio.io/exrates/BTC

**Comment by leomira** [comment]
fixed! 🎉
