### ISSUE TITLE
Feedback Dialogue Optimization

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#613]

**Comment by leomira** [comment]
@SamTremko  the feedback dialogue appears even in a situation when I declined the request deleted the chat -> it should not happen for this scenario

**Comment by SamTremko** [comment]
@leomira which app version do you have? I was fixing this bug like 2 weeks ago

**Comment by leomira** [comment]
@SamTremko 1.9.0, is there a newer one?

**Comment by leomira** [comment]
fixed! 🎉
