### ISSUE TITLE
Maintenance screen 

### ISSUE THREAD

**Issue by mpocuch** [vexl-it/vexl#62]
we need to prepare new screen for a situation that the marketplace is in maintenance mode and cannot be accessed

**Comment by mpocuch** [comment]
ETA 27.9.

**Comment by leomira** [comment]
@mpocuch FYI screen already ready AFAIK

**Comment by mpocuch** [comment]
@leomira yes, thx. just a clarification about the usecase needed (see slack from me today - point 2.)

**Comment by mpocuch** [comment]
@leomira puting the overall maintenance screen (not the marketplace remote config one) to the development for 1.0.10. renaming this ticket to "Maintenance screen".

If marketplace maintenance screen needed to be implemented, please raise in separate ticket

**Comment by leomira** [comment]
Thanks @mpocuch , please don't forget also a separate firebase config for this.
What is the ETA?

**Comment by mpocuch** [comment]
this will be developed and ready for testing within tomorrow, however the production release is driven by the optimizations - which are still in progress. we will let you know the ETA later this week
