### ISSUE TITLE
Allow Vexl to add contacts to phone address book

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#624]
Currently if you add a contact via the Vexl QR code it does not add the contact to your address book. Therefore, if your app is deleted and reinstalled you lose the contacts you added to Vexl via Vexl contacts add. 

Would it be possible to allow an option when importing the contact to Vexl while scanning a QR code to add it to your address book on your phone locally?

**Comment by leomira** [comment]
I am adding a contact manually (not via the QR code) but nothing happens. 
When I try to test via scanning the QR code, the app basically freezes, so I cannot test this scenario (probably because of some backend issues, the whole app does not work properly)

**Comment by SamTremko** [comment]
@leomira this one is still in code review, so not released

**Comment by leomira** [comment]
works well! 🎉 

Couple of things:
1. After successfully saving a number, we are just saving "true" to contacts 😂 please fix this before releasing @SamTremko :D 

2.If I added contact just to my Vexl contacts, I should get a message "You have added XY to your Vexl contacts."

3. if I added contact also to my phone book, I should get a message "You have added XY to your phone book."

4. Please, check the copy on this screen with Grafton, it sounds to me to be a little czenglish :)))
