### ISSUE TITLE
Incorrect number of imported contacts

### ISSUE THREAD

**Issue by soucek87** [vexl-it/vexl#65]
When you import your contacts during the initialization process the nr of your contacts imported is correct. 

However, if you import new contacts afterwards (e.g. you add some new contact), the app doesn't show the correct number of all imported contacts. It shows only the number of contacts you added afterwards. 

The picture below shows: 1 friend (It didn't include all the other contacts previously imported)

![IMG_2348-1](https://user-images.githubusercontent.com/68375745/191507882-799cf510-58d0-4699-a5a9-1c8f4268bd12.PNG)

**Comment by leomira** [comment]
@soucek87 when you open the "Importovat kontakty" button, you see all of the contacts marked? 
Also is this an iOS? Because on Android it works well (tried myself several times).

**Comment by soucek87** [comment]
iOS 15.6.1
iPhone 11

When I open "Importovat kontakty" button, only the recently contact added is marked.

**Comment by soucek87** [comment]
LOL thanks :D 

I re-installed the app, tried it again, and it works now. Not sure what was the problem. (I don't realize I would have deselected any contacts before.)

Anyway, we can close this, I guess.)
