### ISSUE TITLE
Feature request: add Dutch as preferred language option in profile

### ISSUE THREAD

**Issue by jurjendevries** [vexl-it/vexl#653]
I started talking in English to a person who speaks Dutch as well. Later I found he speaks Dutch and he told me Dutch isn't an preferred language option in profile. So it would be nice to have this option. Thank you :-)

**Comment by leomira** [comment]
@jurjendevries well, we will need a dutch translation then :) once it's done, we can ship it in terms of minutes

https://github.com/vexl-it/vexl/blob/main/docs/how_to_help_transalte.md
