### ISSUE TITLE
Common friends list is not updated properly

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#66]
@tomstibor @mpocuch We came across a situation when two users - allegedly 2nd degree contacts - were not shown correct common friends in the chat after the match. 

Both of the users A and B matched before other common friends (C and D) joined the network. The offer of the user A was also posted before this.

However in the chat, only the original common friends were shown and the list did not update and show the users C and D.

We suppose this issue might be connected to #46 .

**Comment by mpocuch** [comment]
@leomira we are currently working on the reencription topic #46 and #22 so if you think it is connected, it might be solved by that. however, in case you want us to look closer on this particular issue, please send us more details to identify the mentioned users

**Comment by leomira** [comment]
@mpocuch might be also connected to #60 and #50

**Comment by leomira** [comment]
working now, I am closing the issue
