### ISSUE TITLE
Emoji not working properly in chat

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#67]
After the latest update, the emojis on iOS don't work properly. 

In the message input, it seems to work correctly, but after sending the message, it breaks. 

Screenshot: 
![signal-2022-09-21-232733_002](https://user-images.githubusercontent.com/25779015/191596801-443984a6-3610-42ca-896b-f06e96543d01.png)

**Comment by mpocuch** [comment]
@leomira is this emojis from iOS16 and displayed on lower iOS version?

**Comment by mpocuch** [comment]
thx for details @akuhtr

**Comment by leomira** [comment]
shipped with 1.0.10
