### ISSUE TITLE
Not being able to send request to an offer

### ISSUE THREAD

**Issue by zaplmi** [vexl-it/vexl#69]
After clicking on send request to an offer it shows following error message:

![image](https://user-images.githubusercontent.com/91535734/191905138-f766f813-3f0b-4b68-926c-1292a4e12db7.png)

1.0.7-295 - iPhone - 16.0

**Comment by prusnak** [comment]
My guess is that this is related to https://github.com/vexl-it/vexl/issues/3#issuecomment-1250047520 - that is, the offer has been already deleted, but the app does not know about it.

**Comment by slush0** [comment]
I propose that the solution of this is to change copy from technical explanation to user explanation. Technically, there's no bug, only confused user.

**Comment by slush0** [comment]
That said, there's a proper solution (#70), but it needs a lot of engineering to fix this particular issue.

**Comment by slush0** [comment]
I propose to fix this particular issue by changing the copy from technical description to something human readable.

There is a proper solution for this to not happening, but it requires a lot of engineering and we probably still cannot cover all corner cases to be sure this never happen again.

Also, this is duplicate to #21

**Comment by zaplmi** [comment]
error message appears also when trying to accept request to own (active) offer.

![Screenshot_20221011-195246 (2)](https://user-images.githubusercontent.com/91535734/195686515-011252d2-d8cc-4cdc-a979-58b12b38cb57.png)

os: Android 11
Vexl 1.0.8

**Comment by zaplmi** [comment]
error message appears also when trying to accept request to own (active) offer.

![Screenshot_20221011-195246 (2)](https://user-images.githubusercontent.com/91535734/195686515-011252d2-d8cc-4cdc-a979-58b12b38cb57.png)

os: Android 11
Vexl 1.0.8
