### ISSUE TITLE
Unable to enter french and british phone numbers

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#72]
Regarding to user review on Google Play (https://play.google.com/console/u/1/developers/5794857065946747658/app/4975074745229843181/user-feedback/review-details?reviewId=6bb0224e-e045-44e1-8a9d-b79c34403caa&corpus=PUBLIC_REVIEWS), users are unable to enter french phone numbers, which are longer by a digit than CZ/SK format. It is necessary to check if the phone number component can handle international phone numbers.

**Comment by leomira** [comment]
@mpocuch this is marked as alpha (before it was in testing) and at the same time as to-be-released 1.0.10
can you please correct the confusion?

**Comment by mpocuch** [comment]
sorry. belongs to waiting for deployment. it is tested on our side and will be deployed on 1.0.10

**Comment by leomira** [comment]
with french I am getting Invalid phone number, with british I am able to enter the whole number, but I get back "Internal server error"

**Comment by leomira** [comment]
seems working, both iOS and Android
