### ISSUE TITLE
Start using geo locations instead of location strings

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#73]
Currently, the offer location is defined simply as a list of strings. There're (not very useful) suggestions on location fields, but currently we cannot display offers on map or even calculate distances and sort offers by distance to the user's claimed location.

To accomplish this, we have to start using better widget for entering locations, maybe even with the possibility to pin on the map, and store choosen locations into the offer in computer readable form (not just "Praha" or "Paralelní Polis".

Later, in consecutive improvements, we may start using this information in marketplace filter, views, for showing map etc.

**Comment by prusnak** [comment]
Originally we wanted to have ~3 GPS locations stored in the offer + radius for each location.
Filter would allow to set ~3 GPS locations and return offers that are within that radius. That means we need to do 3x3=9 comparisons for each downloaded offer to do filtering.

The only real challenge here is entering GPS locations - e.g. which Geocoding service to use.

**Comment by slush0** [comment]
I propose to have only single GPS location in filtering as it IMO fulfills 90+ % of use cases and people can easily make multiple separate searches for different locations.

Having more positions in offer is of course desirable.

That said, this issue is only about implementing geo positioning into Create offer workflow. How and where to use such information (sorting in marketplaces, filtering in filters) should be separate issue as it requires more discussions and separate UX designs.

**Comment by leomira** [comment]
@mpocuch please confirm that this was implemented. if yes, we can close this issue.

**Comment by mpocuch** [comment]
confirmed via Slack -> closing ticket
