### ISSUE TITLE
Checklist/Date & Time: Haptics does not work properly

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#745]
In the calendar view, haptics does not work properly. Please investigate. 
It might be just because of the screen resolution, but I tried several phones with no luck.
Behaviour to be seen in the enclosed video.
Example with date picker: I pick 20, but 19 gets marked.
With date: the haptics does not react to a cross (is does not remove the row.)

Android 14, Pixel 8

https://github.com/vexl-it/vexl/assets/25779015/be16c51a-daa4-4e25-bf22-9acad2646b75

**Comment by leomira** [comment]
this is not fixed, I have the same issue 
Pixel 6, Pixel 8

@kaladivo

**Comment by leomira** [comment]
just wanted to mention that the date picker at #450 works just alright!

**Comment by kaladivo** [comment]
https://github.com/vexl-it/vexl/assets/11568934/78cfa3e2-8124-46ab-a1f2-83eb65f1e330

**Comment by leomira** [comment]
This now works flawlessly @SamTremko @kaladivo 🎉
