### ISSUE TITLE
Checklist: The trade checklist does not refresh after the chat is left by both counterparties

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#746]
When I 
1.) open chat
2.) interact in a chat & checklist
3.) leave the chat

and then counterparty leaves the chat too, once I get to re-request the offer and open a new chat, I see the checklist pre-filled by our previous exchange. 

We can keep the message history, but the checklist itself should reset after the counterparty or a counterparties left the chat.

**Comment by kaladivo** [comment]
I'll take this one. It's a one liner

**Comment by leomira** [comment]
Now the older app gets the prompt after receiving an uncompatible message (checklist message).
But after the update, I cannot see this message in the chat @kaladivo

**Comment by kaladivo** [comment]
@leomira 
We can close this one then. Regarding your last comment. It has its issue here: #750
