### ISSUE TITLE
The user without updated app does not receive warning messages

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#750]
A - updated app
B - not an updated app

When A sends a checklist message to an unupdated app, B does not get the warning about updating the app to the newest version with a link.

**Comment by leomira** [comment]
Given we test on staging, we can use the proper link for an update as we would use on production. I can update manually downloading an APK.

**Comment by leomira** [comment]
probably connected to #701 , but let's at least configure a temporary version, so we can test it properly

**Comment by kaladivo** [comment]
For me, this works from version (1.12.1 (102)).
@leomira what is the issue you are having with this feature?

**Comment by leomira** [comment]
@kaladivo yes, it works from 1.12.1 (102), tested just now

the only issue now is that after I am prompted to update to see a message -> then I update ->  I don't see that message in the chat.
