### ISSUE TITLE
Location pick for checklist keeps crashing

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#753]
I think this is a collection of several issues, but it is hard to replicate. 

Location pick in the checklist acts rather unpredictably and keeps crashing when I try to zoom od de-zoom it. 
You can see it on the attached video.

Please note that on the phone that received the request (Pixel 6) I am wrongly redirected - I save the location, I confirm to send the checklist, but I am redirected back to the map. 

Android 14, on Pixel 6 it allows me to perform at least some actions, on Pixel 8 crashes almost immediately.

https://github.com/vexl-it/vexl/assets/25779015/9b1410ab-9e69-4a3f-a59e-0bfaf917e3cf

**Comment by leomira** [comment]
For some reason, it fails to upload videos of the crashes on the recipients side. Available to you upon request.

**Comment by kaladivo** [comment]
How exactly does the map crash? Does the whole app crash or just the map view gets cancelled? I am having a hard time replicating this

**Comment by leomira** [comment]
fixed! 🎉
