### ISSUE TITLE
Reveal identity: Production bug

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#755]
After
1. revealing identities in the chat (approved)
2. then deleting the chat (both parties)
3. then re-requesting and reopeninng the chat

only the name is shown, the picture is blank. 

2x Pixel 8, Android 14

**Comment by leomira** [comment]
unfortunately, this is not fixed, picture is not saved (at least on the phone where I could)

also, another issue emerged, I am getting an error when trying to upload a picture on the RI recipient's side (both camera & gallery): 

`{
  "_tag": "imagePickerError",
  "reason": "UnknownError",
  "error": {
    "code": "ERR_UNEXPECTED"
  }
}`

Attaching a video below: 


https://github.com/vexl-it/vexl/assets/25779015/71098f13-27e7-4bc2-a93f-46d710d5f4f9


Following by another issue:
While testing re-request, I am not seeing the history of the chat. Also, I don't see the revealed idenity (see that at the same chat, other counterparty, the identity is revealed correctly, however, I dont see the chat history either.)


![Image](https://github.com/vexl-it/vexl/assets/25779015/55a22a67-afdf-4bcc-a418-b356d94b8620)
![Image](https://github.com/vexl-it/vexl/assets/25779015/f20cc1b4-9dab-4df5-aed0-6d450967891a)

**Comment by kaladivo** [comment]
@leomira  
Let's focus only on 1.13.0 version. 

That one behaves as expected (with chat history, identity and checklist) being reset? If so let's close this one

**Comment by leomira** [comment]
all of the above mentioned is related to 1.13.0 @kaladivo 

I have to check the identity reveal problem that I was describing with the imagepicker error - I cannot reproduce it now.

As for the rest, let's just correct the order of the messages in the chat for all the scenarios and then we can close this. 

My point: Vexlbot prompts should be shown always as the last message. 
![signal-2024-01-31-144651_003](https://github.com/vexl-it/vexl/assets/25779015/d55e556f-f315-4f5f-aadd-9b9af67204f3)
![signal-2024-01-31-144651_002](https://github.com/vexl-it/vexl/assets/25779015/b44fe335-0338-4946-9063-7005dc7cb6b7)

**Comment by leomira** [comment]
yes, that behaves as expected
