### ISSUE TITLE
Deleting chat drops the room for the other side instantly

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#76]
When user deletes the chat, it instantly deletes the chat also for other side. Although it may be considered a privacy measure, in practice this prevent users to read already sent, yet unread messages.

User story: After the deal, I want to say thank you to toher side, but I want to leave chat because of housekeeping in my chat window. Currently there's no easy way of doing so, because I even don't know if the other side read the messages yet, to delete the room.

Proposed solution: "Delete chat" drops the chat from my side, but appear as "<user> left the chat. Leave chat, too?" That way, vexlak can cleanup after the deal, yet all previously sent messages can be received by other side.

Please note that technically this can instantly delete chatroom from backend, too. The proposed solution only changes the UI response to the event of deleting room on the receiving side.

**Comment by leomira** [comment]
shipped in 1.0.18
