### ISSUE TITLE
Checklist/Location: Weird styling

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#773]
CTA buttons on this screen are weird and don't respect the style we use everywhere else in the app

![Image](https://github.com/vexl-it/vexl/assets/25779015/3475cdca-45ff-446a-ae69-c8e6ce617e07)

**Comment by kaladivo** [comment]
Fixed: 



![Image](https://github.com/vexl-it/vexl/assets/11568934/1ff91dee-8ba9-4eeb-9139-041f2fc11371)

**Comment by leomira** [comment]
Fixed 🎉
