### ISSUE TITLE
Reveal identity in the chat is lagging on a phone with a lot of contacts

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#774]
On a phone with a lot of contact, reveal identity process in the chat is lagging. I have several videos, if you want to see. 

I don't observe this behaviour on a phone with a smaller network.

**Comment by SamTremko** [comment]
I think connected to https://github.com/vexl-it/vexl/issues/681 as after app comes to foreground after choosing photo it starts fetching contacts from device.

**Comment by kaladivo** [comment]
Yes, that is connected and will require more systematic solution.

Since it's not a blocker, let's focus on other bugs of trade checklist and fix this post release.
