### ISSUE TITLE
Reveal phone number is not prompted in chat after successful reveal identity

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#775]
After we successfully reveal identities, I am not prompted by Vexlbot to reveal my phone number as the next step. 

Android 14, Pixel 6, Pixel 8

**Comment by SamTremko** [comment]
@leomira reveal identity prompt and reveal phone number prompt was not in design. There were prompts only for the rest of the actions. Do we want it to be there?

**Comment by leomira** [comment]
Ah, I totally forgot. Let's skip it for now, I am closing this @SamTremko
