### ISSUE TITLE
Add phone number - Bug in a chat

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#776]
After the successfull phone number reveal (and the whole workflow of adding a contact to Vexl), after I perform any other action in the chat, I keep getting a sticky bar on the bottom of the chat I cannot do anything about.

I have a screen recording available, won't post it here given, that I share phone numbers there.

**Comment by leomira** [comment]
After the successfull phone number reveal (and the whole workflow of adding a contact to Vexl) I keep getting a sticky bar on the bottom of the chat I cannot do anything about. 

I have a screen recording available, won't post it here given, that I share phone numbers there.

**Comment by kaladivo** [comment]
Connected to #681
