### ISSUE TITLE
Notify notify device when registering with the same number on different device

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#784]
folloup on #382. 

When user tries to login with existing phone number on different device, notify device with already existing session for that number.

Will require change on backend.

**Comment by kaladivo** [comment]
@leomira 

I am struggling a bit with the copy here. Could you please help me with that?

![Image](https://github.com/vexl-it/vexl/assets/11568934/87e102c5-b07a-4380-b52b-1bfa9c15ce73)

**Comment by leomira** [comment]
You are trying to log in on a different device!
Make sure that you have deleted all your offers and closed all your trades. The device backup will not be transferred to the new device. 

@kaladivo what do you think? maybe try to finalize it with Grafton to be sure

**Comment by kaladivo** [comment]
Modified according to Ash's suggestions: 

> Make sure that you have deleted all your offers and closed all your trades. **Your data** will not be transferred to the new device.

**Comment by leomira** [comment]
Totally awesome, Ash is a good copywriter :)

**Comment by leomira** [comment]
This is not working - I don't get a warning nor do I get a notification @kaladivo 

BTW: before the warning (issue #382 ) was working flawlessly.

**Comment by kaladivo** [comment]
Works on stage does not work on prod. Investigating

**Comment by kaladivo** [comment]
Works now, fixed on BE
