### ISSUE TITLE
Implement in-app logging

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#79]
Thanks to encrypted nature of the application and communication, it is very hard to debug the application and its corner cases. Please implement view which displays all important events since application startup.

Requirements:

1. If necessary for prevention of memory consumption or performance reasons, it can be disabled by default, with possibility to enable somewhere in Profile section
2. It must log accepted notifications and any network activity on level of API calls and human readable parameters (not necessary to log encrypted values or any binary data)
3. Every entry must contain timestamp.
4. The log should display the most recent event first.
5. The log should not scroll itself when you scroll out of the first line
6. The log should allow selecting the area and copying it to clipboard
7. The log does not need to be persisted anywhere
8. It can be truncated by some number of lines to prevent eating too much memory (beware of freezing of the view in case of many entries in the log

**Comment by leomira** [comment]
shipped in 1.0.10
