### ISSUE TITLE
Friends list popup

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#79]
AC: 
- Friends list as coded in figma
- Should be new Route
   - Accepts parameters: List of encrypted numbers
- Decrypts the numbers and displays name and photo from contact list
- Displays placeholder when photo is missing
- Filters out contacts that were not found
- Is added to: 
  - Offer detail page
  - Chat detail page

**Comment by SamTremko** [comment]
FYI: We decided to implement this one as screen
