### ISSUE TITLE
Unify displaying of Requests and Messages

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#80]
Currently, the very important part of the app - accepting or rejecting notifications - is pretty hidden two click deep in the app: Messages -> Requests. Checking the app after receiving notification then requires checking two places, messages and requests.

I propose to unify these two screens, and let offer request appear in between messages as a virtual chat room. When user rejects the offer, the chat request disappears. In case of accepting it, it turns into chat room in place.

This simplify the management of notifications for heavy users, and remove misunderstanding for newcomers; I has been a witness of multiple users searching for the incoming request in Message tab and completely missing the Requests icon in top corner...

**Comment by leomira** [comment]
shipped Vexl 2.0
