### ISSUE TITLE
Checklist: Order of the messages is wrong again

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#801]
![Image](https://github.com/vexl-it/vexl/assets/25779015/caca9c5e-ad29-4269-85f8-db3d6291b985)
![Image](https://github.com/vexl-it/vexl/assets/25779015/17c2cb13-4eee-45bc-9b1a-20acd583c290)

**Comment by kaladivo** [comment]
Should be fixed in 1.3.1

**Comment by kaladivo** [comment]
![Snímek obrazovky 2024-02-07 v 19 40 43](https://github.com/vexl-it/vexl/assets/11568934/35fec0b2-f445-493c-9ce5-7fb63a76062f)
