### ISSUE TITLE
Location filter overlapping

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#802]
When I add 2 locations to the filters it filters only the offers which have both of them. 
I.e. - I want to filter Prague and Brno. I see only offers which were created for both Prague and Brno. 

Desired behaviour: 
I want to see all the offers that were created for Prague and also all the offers that were created for Brno.

**Comment by kaladivo** [comment]
So it should be `or` not `and`.

**Comment by kaladivo** [comment]
@leomira Can we close this? It does not apply when we have only one filter.

**Comment by leomira** [comment]
yes, closing this 🤝
