### ISSUE TITLE
Swap Buy and Sell tabs

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#81]
There's in general more bitcoin buyers than sellers; that's long-term trend and we see it even in Vexl stats (it's about 3:1 for buying offers). That means more people is looking for a way how to buy bitcoin, thus looking for sellers.

Currently, main tab is a "buying" tab, and the majority of people have to change tabs to see what they're looking for. I propose trivial change of swapping those tabs and display "selling" first.

Please note that I would like to step away from flamewars about how to name buying and selling sides. This issue is purely about displaying that side which is more commonly viewed by users.

**Comment by leomira** [comment]
@mpocuch I see this tabs swapped already, can I close the issue?

**Comment by mpocuch** [comment]
done on AN, TBD in next release on iOS

**Comment by leomira** [comment]
I see it updated on iOS as well?

**Comment by prusnak** [comment]
> I see it updated on iOS as well?

Nope, I still see Predaj Nakup on iOS - Vexl 1.0.8

**Comment by leomira** [comment]
solved
