### ISSUE TITLE
RELEASE BLOCKER: Issues with versioning

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#811]
Testing the latest updates of the app, I came across undesired behavior of the app. 
Below I will try to describe what exactly is happening and attach the screen recordings. 
Pixel 8 - Phone with the newest build 1.13.1
Pixel 6 - Phone with the current production build 1.12.1

**Request sent from 1.12.1., accepted on 1.13.1.**
On 1.12.1, I don't see the checklist (as expected)
On 1.13.1, I see the checklist, but after pressing the button I get a message as it shows on the printscreen.
Expected behavior: The button should be hidden. 
![Image](https://github.com/vexl-it/vexl/assets/25779015/195d46b3-ebe2-49ca-8586-53d7131cdc23)

**After I update 1.12.1 to 1.13.1, in the same, already opened chat**
On the original 1.13.1 (Pixel 8) I get the prompt with VexlBot (as expected).
On the updated 1.13.1, I don't get the prompt by Vexl bot. 
On the updated 1.13.1, I now see the button for checklist. (as expected).
The button for the checklist in the updated app shows a wrong error message (the other side of the chat uses the same version of the app, 1.13.1)
![Image](https://github.com/vexl-it/vexl/assets/25779015/64a3c117-5270-4a8f-a1ad-56769612edd4)

Expected behavior:
Among others, I should get prompt in the both sides of the chat, that means the updated app too. 

**After I update 1.12.1 to 1.13.1, in the newly opened chat**
On the original 1.13.1 (Pixel 8) I don't get the prompt with VexlBot. 
On the updated 1.13.1, I get the prompt by Vexl bot. 
I see the the button on both of the apps (original 1.13.1 and updated one.)
The checklist button does not work on the original 1.13.1, giving error message as on the screenshot above.

Expected behavior:
Among others, I should get prompt in the both sides of the chat, that means the app that was not updated too. 

NOTE - OTHER OUTSTANDING ISSUES: 

- [ ] the order of the messages is still messed!
- [ ] the checklist for online trade is not updated to its new wording (the app updated from 12->13)

**Comment by kaladivo** [comment]
Should be fixed in v 126
