### ISSUE TITLE
Allow negative fees

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#82]
Currently, users can choose in between trading without fees, or for asking for a fee from the other side. However, there's usually a higher demand for buying bitcoins than selling for them, and it is wise to *offer a fee* even for users who create buy offers. That's not possible now, and some people are hot fixing it by offering a fee in description.

I propose to allow setting negative fees (technically speaking; I'm not sure about the actual copy) in Create offer. Then this should be clearly visible in marketplace (maybe with some color difference + changed copy in the fee information) and possibly it should be possible to filter the offers for negative fees in Filter, which can be a sexy feature for professional traders.

Checklist of expected changes:

- [ ] Adapt Create offer view
- [ ] Adapt Offer card
- [ ] Adapt Filter

I also suggest that Create offer should shortly explain the motivation for offering the fee in creating Buy offer, and **set the default to -2% fee**. In Sell offer, I would leave 0% fee by default.

**Comment by slush0** [comment]
My idea of visual changes in Create offer is following:

1. Let's remove radio button "With fee / without fee completely".
2. Show only slider +-7%. Mark negative parts by green grades, positive parts red or yellow grades.
3. Like in password strength, below the slider, explain the chosen value. For this, we will need separate copy for combination of every step (15 steps) and side (buying/selling). Here for example we can explain that offering a fee for buying offer is more desirable and taking a fee is not recommended. While in Selling offer, this can be more in favor of proposing positive fees.
4. The copy can be changed in translations so we can adapt vocabulary to market condition, to give appropriate advices.

**Comment by leomira** [comment]
I propose different naming - let's use "discount" instead. Negative fee is not comprehensible easily.

I consider this part to be a little bit overengineered and I think it would be good if the designer could revisit it. But I understand the idea and I think it is a valuable improvement (however, it is TBD if we want to implement it now).

> My idea of visual changes in Create offer is following:
> 
> 1. Let's remove radio button "With fee / without fee completely".
> 2. Show only slider +-7%. Mark negative parts by green grades, positive parts red or yellow grades.
> 3. Like in password strength, below the slider, explain the chosen value. For this, we will need separate copy for combination of every step (15 steps) and side (buying/selling). Here for example we can explain that offering a fee for buying offer is more desirable and taking a fee is not recommended. While in Selling offer, this can be more in favor of proposing positive fees.
> 4. The copy can be changed in translations so we can adapt vocabulary to market condition, to give appropriate advices.

@slush0 as we are currently working on issue #25 , we have an opportunity to address this at the same time (at least the "create offer" part).

Otherwise we can just keep it simple for now and just redesign the current version with some explanation in place. 
The difference in the workload is not significant, but I think it would be great to have your input for this.

**Comment by prusnak** [comment]
Maybe we can use the following vocabulary:
* negative fee = discount
* positive fee = premium

**Comment by leomira** [comment]
as agreed per chat, I am moving this to "deferred" for now.

**Comment by leomira** [comment]
shipped in Vexl 2.0
