### ISSUE TITLE
Add Namibian Dollars (NAD - N$)

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#827]
At the request of the Vexl community in Namibia can we add Namibian Dollars (NAD - N$)? 

Also "I see that the minimum offer one can make is NAD 1000 which is equivalent to ZAR 1000, is there any way to bring this amount down to a minimum of NAD 20 - 100 as a minimum? I believe this would help with adoption of Bitcoin across my country as the barrier to entry would be greatly reduced."

Could we make some adjustments to the minimums?

**Comment by leomira** [comment]
I can see that we have exactly 0 users from Namibia, @satsdisco ?

**Comment by BigBossRabbit** [comment]
That's weird.

Since I'm Namibia & have the Vexl app & was the person asking for this to be added so that when I get other Namibians onto the app via my Bitcoin events they  actually see Namibian dollars instead of having to do calculations in other currencies. 

This is why it has been requested.

**Comment by stepanborovka** [comment]
There will be meetup with presence of Vexl (idea, why, what,...) in the mid of April, so possible new users from Namibia. Can we reopen the option to add Namibian Dollars?

**Comment by leomira** [comment]
will open the discussion on today's status and update you.

**Comment by BigBossRabbit** [comment]
Yes please, the 1st introduction I will do is at my event this Saturday (13th of April). 

People in Namibia are looking for a simple, easy & safe way to buy & sell their Bitcoin. 

Vexl is the answer they need & will help them see the power of open space & self-custodial solutions.

**Comment by leomira** [comment]
moving this to Todo, @SamTremko will take care of this. 

As for the minimum amount, that's a question for him, how easily deployable it is to change this.

**Comment by SamTremko** [comment]
@leomira @BigBossRabbit there is no such thing as the minimal amount for the offer. You can choose any amount you want by typing in the value into the price input.


![Image](https://github.com/vexl-it/vexl/assets/32439382/498add08-3a37-4ac0-b9f2-74ed47a02e5b)

**Comment by leomira** [comment]
added, seems to work fine, ready to be released

**Comment by leomira** [comment]
@BigBossRabbit this should be released now, check it out if you can see the recent update!

**Comment by BigBossRabbit** [comment]
Checking now. One moment please

**Comment by BigBossRabbit** [comment]
Yay!! It's in there. I'm even more excited about Saturday now. Thank you all for the great work & amazing product you created 🥳![image](https://github.com/vexl-it/vexl/assets/87260669/a520fed6-c380-49c0-817e-e6b94e1f3be3)

**Comment by leomira** [comment]
Good luck with the meetup and let us know how it went! 🚀
