### ISSUE TITLE
Display part of phone number in Reveal identity

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#84]
At current state (prior implementing Verified contacts), even having common friends and displaying name and avatar in Reveal identity isn't enough to build the trust that the other side is who she claim it is. There's no easy way how to ask common friend for recommendation when we give no verified handle to the person we are talking to.

I've been even a witness of people surprised that Reveal identity didn't show full phone number. I'm myself against revealing full phone number here as it can be used for build fake trust in the app. Attacker can convince people to reveal their identity without even an intent to finalize trade with them, twisting the incentives in the app.

Proposal:
In Reveal identity feature, show country prefix (that's mostly UX thing for people understanding the number is a phone number) and three (two?) trailing numbers of contact phone number. That way we give something which has been proven by Vexl (as the user have to register with SMS into the app with this phone number) to verify by asking common friends.

Example: +420 *** *** 078 (+ verified badge ✅)

**Comment by leomira** [comment]
shipped in Vexl 2.0
