### ISSUE TITLE
Iphone UI is lagging during scroll

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#86]
On Iphone (at least Iphone 11) the whole marketplace UI is rather slow and lagging when scrolling the offers. It's much slower than on Android, which is rather surprising.

**Comment by prusnak** [comment]
On Android the chart on the top does not move away, on iOS it does and it is very slow.

Fix: let's fix the chart position on top on iOS, so it does not scroll away.

**Comment by leomira** [comment]
shipped in 1.0.17
