### ISSUE TITLE
Map: Default map view

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#864]
If possible, I propose having the default view of the map according to where does the user have the most offers. 

Iam not quite sure how it works right now, but I don't get the logic how it initially zoomes after I switch from list view to map view (see below).

If this is not possible, we can also come up with a different logic, but it should feel intuitive. 

![Image](https://github.com/vexl-it/vexl/assets/25779015/d5eb0c61-22a6-4b62-acfa-1af775a3c90c)

**Comment by kaladivo** [comment]
That is not trivial, let's talk about this. We need to find a way how to calculate the location with the most offers...

**Comment by leomira** [comment]
@kaladivo and what is the default now?

**Comment by kaladivo** [comment]
As we discussed on Monday's call: 

- If you are on offer detail, it shows offer location
- If you have location  filter selected it shows filter area
- Tries to fit all offers (meaning their radiuses) to the view 
- If there are no offers for some reason all all other conditions are not met, it shows Europe as a fallback (should not happen)

**Comment by leomira** [comment]
@kaladivo my question is: once you log into the marketplace for the first time, what is the default zoom of the map?

**Comment by kaladivo** [comment]
To fit all offers to the view

**Comment by kaladivo** [comment]
OR your filter if you have set any

**Comment by leomira** [comment]
Can we group it and show a number of offers per city/area? Similar to how Zasilkovna does it?![Screenshot_20240308-105116.png](https://github.com/vexl-it/vexl/assets/25779015/4b0711b0-cadc-45c5-a989-01ed687b9490)

**Comment by kaladivo** [comment]
How is that related? 

I have done some tests with 100 - 1000 offers on the map and the performance was fine. 

The problem with this approach is it does not take into consideration radiuses. But we can do it if you think it makes sense in our case.

**Comment by leomira** [comment]
Have you responded to the right issue? I did not mention anything about performance and performance is not my concern.
I am just wondering if we can group the offers as Zasilkovna does and show the amount per particular area - it is just an UI update

**Comment by leomira** [comment]
Attaching here what I already wrote to #887 

Partial solution to the problem could be if we were able to change the default view to i.e. an area with the biggest concentration of offers. IMO this does not even have to be exact, it could be some dummy condition like "by default zoom in to the most common city in your marketplace") - even if you then got the initial zoom to Prague and you are from Brno, it is still better and much more usable than having the current situation. You can than just set a filter and problem would be solved.

I say partial because it would still not solve the situation in places where the offers are concentrated (i.e. district cities or capitals).

We need to have this defined also because of our BTC Prague strategy. 

Another approaches that come to my mind:
Pre-filtering at least according to a country (per country code) - however, this is insufficient
Pre-filtering according to what a user sets (prompting them to set the filter)

**Comment by leomira** [comment]
The current solution is sufficient, I am closing this for now
