### ISSUE TITLE
Map: Don't show street names in offers

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#865]
Let's not show the street name in the offer card. This is noised anyway. Let's use a city, or District + City. 

![Image](https://github.com/vexl-it/vexl/assets/25779015/946a575f-c5b6-4bba-bf3a-1a577d5f2899)

**Comment by kaladivo** [comment]
All new offers created will have city in address text (if possible ofc). This might me some offer from testing...

**Comment by leomira** [comment]
Some of the offers still have streets instead of city.


![Image](https://github.com/vexl-it/vexl/assets/25779015/1d3a981d-8af0-408d-ae4c-23ecf4a125f0)
![Image](https://github.com/vexl-it/vexl/assets/25779015/db70a638-d793-42e4-8649-4bddeb9552ca)

**Comment by leomira** [comment]
Also, some offers are showing the ZIP code? Please remove it 🙏  (this is my offers list)
![Image](https://github.com/vexl-it/vexl/assets/25779015/42d1a12c-4a68-430e-b71e-018adcc2c575)

**Comment by leomira** [comment]
fixed! 🎉 
I can't quite distinguish why, but some places are shown with ZIP codes. It is not a release blocker, but it would be nicer to have it without.

**Comment by leomira** [comment]
here are some examples: 


![Image](https://github.com/vexl-it/vexl/assets/25779015/30d31ee8-5b49-4e71-ac30-9c3108e34016)
![Image](https://github.com/vexl-it/vexl/assets/25779015/13429e03-8b74-460f-a56a-24afad33a806)
