### ISSUE TITLE
Map: Size of the circle

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#869]
In the printscreen (+ video) below I am clicking on an offer with two locations. I get zoomed to the second location as well, and the circle around the offer is unproportionally bigger.

Can we fix the proportions and have it the same? Or is it directly dependent on radiuses? 

![Image](https://github.com/vexl-it/vexl/assets/25779015/3591d00b-7634-4421-b630-1d5820d5a7bd)

**Comment by kaladivo** [comment]
The circle is representation of the radius.

**Comment by leomira** [comment]
Gotcha. Gonna close this.
