### ISSUE TITLE
Map: Visual noise due to map's opacity

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#870]
Please see on the caption below (where I move the map around) - thanks to the imperfect opacity, the map feels like it visually noised (see particularly from 0:05)

https://github.com/vexl-it/vexl/assets/25779015/5568bee8-8ef2-4762-89ea-89229fac8011

**Comment by kaladivo** [comment]
Sadly, I don't see what you mean... Could you please upload higher res video? I am not getting any visual "noise" on my device and I am not sure if what I see on the video are downres video fragments.

**Comment by leomira** [comment]
Unfortunately, not solved. I think that the only problem is that the underlying map's opacity is too low. Can you check it one more time? 


https://github.com/vexl-it/vexl/assets/25779015/f2c196a6-d5e4-4d44-82f3-bbc107cf7640

**Comment by leomira** [comment]
@kaladivo fyi, v trade checkliste je to uplne v poriadku.

**Comment by kaladivo** [comment]
Tried to simulate this on different devices and emulators. Unsuccessfully, so far. 

I tried to add a new black layer behind the map. Let's see if that fixes it. If not I'll try to find a Pixel 8 to try to replicate it that way.
