### ISSUE TITLE
Map: Haptics is irresponsive to tap

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#871]
Please see video below (from 0:10 on) - the haptics acts a bit funky and unpredictable. Can we increase the area around yellow dots where it would respond?

**Comment by kaladivo** [comment]
I don't follow, do you want to add haptic feedback when user presses on the map point or do you just want the click area to be larger?

**Comment by kaladivo** [comment]
I have increased the touch box to have 20px width / height. Now, the problem is with them overlapping. Let's see, if that would work.

**Comment by leomira** [comment]
I am not sure if this is because of this solution, but we introduced additional glitching. Haptics did not improve too much as well, see the attached video :/ 


https://github.com/vexl-it/vexl/assets/25779015/e63296cc-677b-42a1-9bd8-187a9bf26493

**Comment by leomira** [comment]
Overlapping could be solved by implementing #887

**Comment by kaladivo** [comment]
> Overlapping could be solved by implementing https://github.com/vexl-it/vexl/issues/887

not really, if the centers of the offers are too close together

**Comment by kaladivo** [comment]
Connected to this: https://github.com/react-native-maps/react-native-maps/issues/4997

**Comment by kaladivo** [comment]
I increased the size of the touch box around the offer marker to be 28x28 pixels.

Here is a visualization: 



![Image](https://github.com/vexl-it/vexl/assets/11568934/38856d3d-6bbd-4406-bda2-92fa1b3d958a)

**Comment by leomira** [comment]
fixed! 🎉
