### ISSUE TITLE
Adding Colombian Peso COP

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#894]
As we expand Vexl into other communities one of the issues we are facing is that not all currency pairs are available in the app. While the price of btc won't be reflected due the currency not being in coingecko's API. That being said people will still like to offer bitcoin in their local currency. 

At the request of a Vexl user in Colombia can we add the Colombian Peso to Vexl so that offers can be created with COP as the trading pair.

**Comment by leomira** [comment]
moving this here, I see it released and working on Staging

**Comment by leomira** [comment]
ah, sorry, not working. 

I am moving this to "in development". 

![Image](https://github.com/vexl-it/vexl/assets/25779015/804e8eb6-7d57-4f19-abb3-fae92dba6ff8)

Pls make sure we hide it from the list when we will be releasing the staging to champions until it is not fixed @SamTremko @kaladivo

**Comment by leomira** [comment]
not supported by coingecko, moving this to Blocked

**Comment by satsdisco** [comment]
Should we not treat this like the Namibian Dollars?

**Comment by leomira** [comment]
It is not pegged nor equivalent to any of the currencies supported by coingecko.

**Comment by HostFat** [comment]
https://api.yadio.io/exrates/COP

#980

**Comment by leomira** [comment]
connected to #980
