### ISSUE TITLE
Trading checklist price offer pending 

### ISSUE THREAD

**Issue by kaladivo** [vexl-it/vexl#928]
> Vcera jsem pri vexlu hitnul bug. Poslal jsem nabidku ceny, protistrane prisla, ale kliknuti na tlacitko "akceptovat" nic neudelalo a na me strane byla castka stale pending. Kdyz protistrana sla do Editu a klikla na Aktualizovat (nepamatuju si presne ty labely tlacitek), tak se to potom na me strane projevilo.

**Comment by leomira** [comment]
@SamTremko tohle je pravdepodobne jiz taky fixed, am I right?

**Comment by SamTremko** [comment]
@leomira I am not sure about this one. It can be connected to sth else there. Let's keep it here, so I can have a look when I have some time, to check the process. I think this is not connected to the bug, that we were fixing on PROD with trade checklist.

**Comment by leomira** [comment]
fixed 🎉
