### ISSUE TITLE
Add Italian and polish

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#930]
The translations are ready for dev mod in the app. The translations of Italian and polish can be added to debug mode for the translators to perform last checks before going live.

**Comment by leomira** [comment]
seems to be added to dev mode. 

@satsdisco pls note that italian is translated (I am not sure if the whole app), but polish not.

**Comment by satsdisco** [comment]
I didnt mean to open a new issue, my mistake, but the polish translations should be ready as well as the italian ones, according to the translators.
