### ISSUE TITLE
Trade checklist won't accept a bitcoin taproot address

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#939]
When filling out the trade checklist in a vexl chat taproot address give invalid BTC address error. 

Other addresses work fine. 

![IMAGE 2024-04-02 13:49:39](https://github.com/vexl-it/vexl/assets/143531040/077775e3-af4e-4ac2-8127-f4e77292b5f4)

**Comment by leomira** [comment]
fixed! 🎉
