### ISSUE TITLE
Update offer: Listing type

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#942]
Below, I propose couple of updates of the current update flow. They are all connected to offer form. I consider them to be rather minor, so I am batching them into one issue.

- [x] Indicate that there is a missing listing type. We can use a red exclamation point instead of the icon for this case? Or any other idea? 
![Image](https://github.com/vexl-it/vexl/assets/25779015/84a9483e-07eb-45d4-b051-27723f6a4c93)

- [x] Make choosing the listing type mandatory. Show error: Please fill up a listing type (same as with i.e. unfilled location.)
- [x] Change copy for the delivery method warning. "Pickup in person is safer. Never share your home address with anyone you don’t trust."
- [x] Change the order of the currencies: CZK first, SATS second

![Image](https://github.com/vexl-it/vexl/assets/25779015/3827c2f4-e3a2-46b9-8c41-4cd04a442e91)

**Comment by SamTremko** [comment]
@leomira I have done the first point like this:


![Image](https://github.com/vexl-it/vexl/assets/32439382/2175aa5d-96c3-441d-ae41-a44da2189a26)

It is the simplest solution in current implementation. Adding exclamation mark next to the title would introduce some complexity to code. And this will do the same thing. Let me know what you think.

**Comment by leomira** [comment]
It is great, let's ship it :)

**Comment by leomira** [comment]
fixed and ready to be shipped! 🎉
