### ISSUE TITLE
Price format in the marketplace without categories

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#946]
I know we have a range as a default setup in the marketplace without categories.

Would it be possible just to show a single number instead of range for the offers from new vexl, where the price is set? 

![Image](https://github.com/vexl-it/vexl/assets/25779015/91a3871f-5692-44ed-84db-0c9c91ee3935)

**Comment by SamTremko** [comment]
@leomira I suppose this is screenshot from the old vexl app before update and the offer shown is Product/Other offer, which is displayed by the old app.
Here we cannot do anything about this as we are using the same attributes for the price property in Offer payload, that are used by old BTC offers (amountBottomLimit and amountTopLimit). To explain that, when user sets price on some product to be 2000 USD, this value will be assigned to both attributes amountBottomLimit as well as amountTopLimit. This way the old app can display the price for the product but its in a little weird way as in the picture above. New versions will display price in SATS for product and other listing type offers and range, as on the picture above, for BTC offers only.

**Comment by leomira** [comment]
@SamTremko understood, couldn't we tweak it a bit, and maybe for this kind of offers not show the bottom or top?

**Comment by leomira** [comment]
but it would probably require an update of the app, am I right

**Comment by leomira** [comment]
and that does not make sense, as in the new app we already have it :D

**Comment by leomira** [comment]
if that's the case, let's close this

**Comment by SamTremko** [comment]
Long answer:
Yes its exactly like that. We are using amountBottomLimit property as the main one for the new price information in Product/Other offers. And the display of the value on marketplace that you are talking about is based mainly on the condition that if the amountBottomLimit > 0 then display price range otherwise display "Up to #somePrice" formulation.

Short answer:
Yes we would need to update the old app :D

**Comment by SamTremko** [comment]
Short and efective solution: Let's close it :D
