### ISSUE TITLE
Add Japanese translations

### ISSUE THREAD

**Issue by alexandre-k** [vexl-it/vexl#950]
The translations are ready for dev mod in the app. The translations of Japanese can be added to debug mode for the translators to perform last checks before going live.

**Comment by leomira** [comment]
Guys @SamTremko @kaladivo if this is ready, we can add it to the debug screen with the next release. But it has a low priority.

**Comment by SamTremko** [comment]
@leomira if we have translations ready, I can add it, its quick task

**Comment by alexandre-k** [comment]
@SamTremko Yes it is ready, I did all the translations on Crowdin.
Only the terms of the service was done through an automated translation tool.
