### ISSUE TITLE
Option to select multiple fiat currencies

### ISSUE THREAD

**Issue by stepanborovka** [vexl-it/vexl#951]
Idea of the improvement. Something similar to selection of multiple languages. I know it is not similar, but some people will benefit from it.

We've got a feedback that for example people in Bulgaria quote in BGN (local cur) but also in EUR, so is it possible to allow multiple fiat currency selection?

**Comment by leomira** [comment]
This can be easily achieved by creating 2 offers. I think this is for now very marginal problem, I will close this and we can revisit it in the future if the need will arise.
