### ISSUE TITLE
Ditch icons on buttons

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#967]
![Snímka obrazovky 2024-04-11 o 14 23 11](https://github.com/vexl-it/vexl/assets/25779015/63164687-6558-4231-ada7-7b0f5e976afd)

**Comment by leomira** [comment]
![Snímka obrazovky 2024-04-11 o 17 23 59](https://github.com/vexl-it/vexl/assets/25779015/439a4065-d1ea-43f4-b297-57b7ca6e1d0d)
![Snímka obrazovky 2024-04-11 o 17 25 02](https://github.com/vexl-it/vexl/assets/25779015/b07ba3b8-6b33-428d-9608-166eb608d9d3)

**Comment by SamTremko** [comment]
I will also add here one more thing: Change background colour for Map/List button, as it has the same colour as offer bubble in already requested state.
![image](https://github.com/vexl-it/vexl/assets/32439382/d503eab9-2175-4ac7-a854-f52aeea90aee)
![image](https://github.com/vexl-it/vexl/assets/32439382/56588e94-9879-481f-8249-98e41d4c8940)
