### ISSUE TITLE
Force display on for re-encryption screen

### ISSUE THREAD

**Issue by slush0** [vexl-it/vexl#97]
Currently the reencryption process is getting interrupted by display going dark after some time of user non-activity. It makes the reencryption slower-than-necessary, because user have to wake up display repeatedly for process to continue.

There's a possibility to force display to stay on for this process. Thanks to this, the reencryption can continue without a user interaction easily.

**Comment by leomira** [comment]
Let's connect implementation of this with #96

**Comment by slush0** [comment]
@leomira I don't think it anyhow relevant (technically). #96 is primarily API/DB change, and display is frontend tuning.

**Comment by leomira** [comment]
It was more of a comment for Michal regarding next spring planning, so from
this perspective it is relevant

**Comment by prusnak** [comment]
This is how it's done on Android:

https://stackoverflow.com/questions/6290094/android-disable-screen-saver
