### ISSUE TITLE
Set up unit tests for apps/cli

### ISSUE THREAD

**Issue by PanJarda** [vexl-it/vexl#97]
There are no unit tests for apps/cli package. Also the code is hard to read and reason about for people not familiar with `fp-ts`. Proper test coverage would help to achieve document intended functionality and improve maintainability.

**Comment by kaladivo** [comment]
Not really sure if this is the priority. We will certainly look into this once we start writing backend tests. 

The CLI is meant as a tool for developers / tool for testing. It is much faster to run a few commands to simulate certain scenario than to simulating the state by interacting with the app.

**Comment by leomira** [comment]
solved
