### ISSUE TITLE
Contacts polishing

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#972]
Let's use the designers suggestions and have here tabs instead of filter. Take the inspiration from Revolut. (Please watch the Miro recording for how exactly to use this. 
As a part of this update, let's polish the copy as well.

I suggest dividing the tabs to:
Submitted 
Non-submitted
New

Other minor updates: 
-[ ] Update empty space (see #970 )
-[ ] empty New state: 
Vexlak
Copy: To be kept as we have it now (BUT BLACK HEADLINE)
CTA: Add a number

**Comment by leomira** [comment]
Please check #1084 when working on this 🙏

**Comment by SamTremko** [comment]
Check also the images of common contacts, as the are missing:
![Image](https://github.com/vexl-it/vexl/assets/32439382/ef331df0-3eb7-42ae-ad4c-7da8e211ef9b)

**Comment by SamTremko** [comment]
Check also the photos of common contacts, as they seem to be missing in some scenarios

![Image](https://github.com/vexl-it/vexl/assets/32439382/0ad5b88b-8004-4226-85de-7273f94c3b81)

**Comment by leomira** [comment]
yayyyyy works flawlessly! 🎉

**Comment by leomira** [comment]
@SamTremko I propose one final update: 
let's change the order of the tabs in the Contacts screen: 
1. New
2. Non-submitted
3. Submitted

**Comment by leomira** [comment]
all fixed!!! 🎉
