### ISSUE TITLE
Chat & Reveal Identity polishing

### ISSUE THREAD

**Issue by leomira** [vexl-it/vexl#973]
CHAT:
- [x] Update yellow point both in the bottom panel and in the chat list: make it smaller and closer to the icon.
- [x] Keep number of friends with icon. 
- [x] Update the text input in chat in order to be consistent with the rest of the elements in the app.

TRADING CHECKLIST:
- [x] Resize the font of the headline, so the whole checklist will be more visible.
- [x] Add warning when leaving an unsent checklist.
- [x] Calendar component update. 
- [x] Ditch the edit icon, add button "Change".
- [x] Ditch the button design, keep normal font without background.

CHAT:
Yellow point: 
![Snímka obrazovky 2024-04-11 o 18 25 09](https://github.com/vexl-it/vexl/assets/25779015/03022748-5d59-48a6-bee1-127822c8c17d)
![Snímka obrazovky 2024-04-11 o 18 25 19](https://github.com/vexl-it/vexl/assets/25779015/4fc65c50-4607-4b59-b172-afe9503a23c9)
Icon + number of friends together: 
![Snímka obrazovky 2024-04-11 o 18 25 30](https://github.com/vexl-it/vexl/assets/25779015/b928b4a4-b9f0-4b01-ac13-617d5903d315)
Chat input update: 
![Snímka obrazovky 2024-04-11 o 18 26 16](https://github.com/vexl-it/vexl/assets/25779015/b6ac9a5f-9301-447f-b0c3-a3b49384ce0c)

TRADING CHECKLIST:
Resize font + warning notes: 
![Snímka obrazovky 2024-04-11 o 18 40 17](https://github.com/vexl-it/vexl/assets/25779015/b5a5b8e5-92f8-4259-82a2-f31669c7a636)
Calendar component what we want: 
![Snímka obrazovky 2024-04-11 o 18 32 50](https://github.com/vexl-it/vexl/assets/25779015/0c4f395e-2080-4332-9b76-c8de1cce5217)
Ditch icon, add button:
![Snímka obrazovky 2024-04-11 o 18 35 26](https://github.com/vexl-it/vexl/assets/25779015/73070f2a-cb6e-4550-87d4-958b814f5110)
Ditch button design, keep normal font:
![Snímka obrazovky 2024-04-11 o 18 36 55](https://github.com/vexl-it/vexl/assets/25779015/2a01d24d-ff25-4724-82df-0a09f71d7f17)

**Comment by leomira** [comment]
- [ ]  Keep number of friends with icon. - not fixed
- [ ] We lost the whole workflow with accept/change buttons :D Now there's just "Respond", we can never agree.

Btw, the gulička in calendar component is beautiful!

**Comment by SamTremko** [comment]
@leomira but the "Respond" button has always been there. Its displayed for options, where user has to confirm the option from multiple, or confirm the option on mapview. The only change was for the Amount VexlBot message, where 2 parties are discussing the price.

**Comment by leomira** [comment]
Aha oki, @SamTremko will try out again

**Comment by leomira** [comment]
works well! 🎉
