### ISSUE TITLE
Add Lebanese pound (LBP - L£) to supported currencies

### ISSUE THREAD

**Issue by stepanborovka** [vexl-it/vexl#977]
At the request of the Vexl community in Lebanon can we add Lebanese pound (LBP - L£)? 

If so, use exchange rate from the website below, because: 

> For hyperinflationary countries like lebanon, there are multiple exchange rate for the local currency to the dollar. You can’t offer bitcoin price exchanged at the Google exchange rate, no one will buy it. Instead, use the market’s.

https://lirarate.org/

**Comment by stepanborovka** [comment]
Unfortunately Lebanese pound is not supported by CoinGecko API, neither is pegged to other currency.

**Comment by HostFat** [comment]
https://api.yadio.io/exrates/LBP

#980

**Comment by stepanborovka** [comment]
Somebody even recommended this one:
https://yadio.io/grid.html 
but still the list is not completed, so right now we are using CoinGecko as a source but for the future let's explore better ways to have more supported currencies.

**Comment by leomira** [comment]
connected to #980
