### ISSUE TITLE
Add the support for yadio.io API as alternative to Coingecko

### ISSUE THREAD

**Issue by HostFat** [vexl-it/vexl#980]
Yadio.io supports more fiat currencies then Coingecko.

https://yadio.io/api.html

By adding the support for it, you can add the support for many more fiat currency exchange rate on your app.

**Comment by kaladivo** [comment]
Questions to answer to ensure that we can use this safely: 
1. What is the pricing of the API? 
2. Are there any quotas?
3. Are there any requirements from the service that we need to meet before using the API (Display some text or some image, etc...)? 
4. Is it ok if we catch the value (some APIs forbid this)?

@stepanborovka you have looked into this, have you found anything?

**Comment by leomira** [comment]
after speaking with them and @kaladivo I think this looks like a solid candidate for our new price source, thanks @HostFat .

moving this to todo, let's give it a try @kaladivo

**Comment by HostFat** [comment]
There are many fiat currencies available on Yadio, I hope that you will add all of them, or most of them :)
