### ISSUE TITLE
Check trade checklist workflow works correctly

### ISSUE THREAD

**Issue by SamTremko** [vexl-it/vexl#981]
Check that trade checklist works correctly in between versions. What happens if one side has old version, that does not accept trade checklist messages, or do not even show user, that he needs to update to see the trade checklist message. And also other combinations of scenarios.

![Image](https://github.com/vexl-it/vexl/assets/32439382/7bcf55f3-3d29-435e-a1f3-57ca473bf25e)

**Comment by leomira** [comment]
@SamTremko is this still relevant? I think we solved it, nope?

**Comment by SamTremko** [comment]
@leomira yes you are right, it was solved with the fix on PROD few days ago, I will close it

**Comment by SamTremko** [comment]
Resolved in PROD hotfix
