### ISSUE TITLE
Swapping contacts via QR Code

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#993]
For simple swapping of contacts and growing network using in app QR Code, the messaging needs to be clearer to set the name of the person you are swapping contacts. 

Currently, if you haven't set up your Vexl Identity yet, it shares your anonymous vexl name, and is often skipped in a hurry as the exchange is made to be done quickly, and the its very easy. 

So when scanning QR code to swap contact before importing needs to be clearer.

**Comment by leomira** [comment]
Please, fix this directly in crowdin.
