### ISSUE TITLE
Allowing camera permissions crashes Vexl iOS

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#994]
Upon granting camera access after installing Vexl on iOS devices, the app crashes and a notification appears saying Vexl 2.0 Crashed. 

replicated many times

**Comment by leomira** [comment]
@satsdisco share a recording pls

**Comment by satsdisco** [comment]
Let me elaborate here. 

When a user downloads the app for ios for the first time and goes through onboarding, after navigating to the profile screen to swap contacts via QR code and taping the camera icon in the top right of the app, the app immediately crashes and displays a notification vexl 2.0 crashed.
